### ISSUE TITLE
Runtime observation

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1355]
Tasks related to instrument and use data from any runtime.

Issue migrated from JIRA: 
https://issues.jboss.org/browse/KIALI-916

Issues:
- [X] Custom raw metrics: allow different aggregations than "sum"
- [X] [Research] Support to "observe" container runtimes
- [X] Document Kiali's goal with runtime observation
- [X] Show runtime information and icon
- [X] Link to runtime grafana dashboard
- [X] [RS] Runtime observation: POC
- [X] Show runtime metrics for App and Workload
- [X] Runtime monitoring: get runtime type from image label
- [X] Provide dashboard and health templates for RHOAR runtimes
- [X] Runtime monitoring: document feature
- [X] Runtime metrics: allow display of gauges/counter
- [X] Dashboards: dissociate runtimes vs dashboards in model
- [X] Runtimes metrics: group by version
- [ ] Build EAP dashboard https://github.com/kiali/kiali/issues/1358
- [ ] Investigate ServiceMonitor to bind pods and dashboards https://github.com/kiali/kiali/issues/1357
- [ ] Use runtime health in health checks https://github.com/kiali/kiali/issues/1356

**Comment by lucasponce** [comment]
I think a first end-to-end flow in the runtimes monitoring feature is already implemented and documented:
https://kiali.io/documentation/runtimes-monitoring/

Future additions to more runtimes can be added, but I consider the epic delivered and close.
