### ISSUE TITLE
Multitenancy Tasks for Kiali

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1359]
Issue migrated from JIRA:
https://issues.jboss.org/browse/KIALI-1191

Issues:

- [X] Reduce permissions needed to install and run Kiali
- [X] Sync with Maistra on Multitenancy
- [X] Use user credentials when contacting the k8s master
- [X] OpenShift Oauth Login
- [X] [RS] Multitenancy with Jaeger
- [X] [RS] Research multitenancy options
- [X] 'all' namespace with multitenancy	Task
- [X] Multitenancy metrics filter
- [X] Jaeger Multitenancy
- [X] Cross namespace support with multitenancy
- [X] Prepare backend for allowing switching of token
- [X] [QE] KIALI-1186 Use user credentials when contating k8s master
- [X] Handle multitenancy with the Jaeger components
- [X] Allow accessing protected p8s
- [X] Ability to filter namespace based on a label
- [X] Handle connections to Grafana which are protected
- [X] Handle Jaeger connections with authentication	
- [ ] Multitenancy with P8S and Grafana	https://github.com/kiali/kiali/issues/1360	
- [ ] Kiali Multitenancy https://github.com/kiali/kiali/issues/1361
- [ ] Update the side panel for inaccessible components	Dev Task	NEW	Unassigned

**Comment by mwringe** [comment]
This issue has already been resolved. Closing

**Comment by lucasponce** [comment]
@mwringe please, update #1361 as well and the list of issues linked, if needed.

I used this one as test.
