### ISSUE TITLE
Multi-cluster support (replicated control plane)

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#1363]
When you have istio spanning multiple Kubernetes clusters, kiali will only list namespaces that live on the cluster where Kiali runs.

There is a flag istio/multicluster. If that is true, we should look for a secret that contains kube configs for the other clusters and use those to talk to the remote clusters and pull their data in.

the main istio control plan can be informed that there are other cluster federated by the fact that there are secrets with the following label:
istio/multiCluster=true

The content of the secret is a kubeconfig file that can be used to connect to the other cluster.
There can be multiple of such secrets.

Issue migrated from Jira:
https://issues.jboss.org/browse/KIALI-1797
https://issues.jboss.org/browse/KIALI-2584 (most details here)

--

**Tasks for replicated control plane setup (previously known as _multiple control plane_):**

- [x] Explore how the scenario works and create issues to track progress
- [x] #1364 Versioned graph support for virtual service routing
- [x] #1365 App graph support with virtual service routing
- [x] #1366 Service graph support with virtual service routing
- [x] #1367 Workload graph support with virtual service routing
- [x] #1480 Adequately find incoming traffic from other clusters
- [x] #1481 Adequately identify service nodes when being called remotely
- [x] #1613 Display ServiceEntries in traffic tab
- [x] Write docs in the website
- [x] Check the traffic-through-egress case
  - I saw no difference in metrics in this case. So, there is nothing to change.

**Comment by lucasponce** [comment]
Related:
https://discuss.istio.io/t/kiali-and-jeager-with-shared-control-plane/3640

**Comment by israel-hdez** [comment]
Multi-cluster seems to be partially broken in the coming Istio 1.3 release. Reported in https://github.com/istio/istio/issues/16890.

**Comment by israel-hdez** [comment]
Reducing scope of this issue only to the replicated control plane case.
The shared control plane case is being tracked in https://github.com/kiali/kiali/issues/1833.
