### ISSUE TITLE
Graph side-panel updates

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1417]
After the PF4 migration, the graph side panel is too big.

This is a 1440x900px screen resolution. With this resolution, (at least for me) the side panel is very distracting and also is borrowing a lot of screen space, turning the graph small.

Looking at this survey:
http://gs.statcounter.com/screen-resolution-stats/desktop/worldwide

the screen resolution of 1366x768 is the most common one (which is smaller than the one of my screenshot). Although Kiali graph may look OK on the second most common resolution (which is 1080p), it should be a concern to make the graph look OK on the most common one.

JIRA:
https://issues.jboss.org/browse/KIALI-2742

**Comment by jshaughn** [comment]
New side panel design issue: https://github.com/kiali/kiali-design/issues/149

**Comment by mtho11** [comment]
@jshaughn looks like the design issue was updated today.

**Comment by jshaughn** [comment]
This is an incremental task for side panel improvements and dev console l+f synchronicity,  The following work has currently been green-lighted :

- [ ] remove the "label" badging in the side panels, it's visually distracting and does not add much information.
- [ ] add a right-adjusted Actions dropdown that mimics the context-menu for the node
- [ ] Work on consistent font use (see Dev Console)
- [ ] White background for Chart headers (see Dev console)
- [ ] size reduction for charts
