### ISSUE TITLE
Include Sidecar (resource, not the proxy) validations

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1541]
I would like to see validations running on my sidecar resources: https://istio.io/docs/reference/config/networking/v1alpha3/sidecar/

> NOTE: Each namespace can have only one Sidecar resource without any workload selector. The behavior of the system is undefined if more than one selector-less Sidecar resources exist in a given namespace. The behavior of the system is undefined if two or more Sidecar resources with a workload selector select the same workload instance.

It also should include the following validations:
- [x] There are workloads with the provided labels in the `workloadSelector` field.
- [x] There aren't two sidecars in the same namespace without `workloadSelector`.
- [x] There aren't two sidecars pointing to the same workload
- [x] IstioEgressLister `hosts` have to be in namespace/dnsName format.
- [x] IstioEgressListener `bind` must have format: x.x.x.x or unix:///path/to/uds or unix://@foobar
- [x] IstioIngressListener `bind` must have  `x.x.x.x` format.
- [x] Global Sidecar (placed in root Namespace) should not have `workloadSelector`

~~IstioEgressListener `hosts` field to ensure access to istio-system services (for both telemetry and policy services)~~ (Only need if you use mixer. Istio 1.5 deprecated Mixer. Not necessary anymore)

JIRA:
https://issues.jboss.org/browse/KIALI-3120

**Comment by lucasponce** [comment]
Now that Kiali can generate Sidecars, it would be worth if validations logic is updated with these scenarios.

**Comment by xeviknal** [comment]
Adding the following validations:
- [ ] There are workloads with the provided labels in the `workloadSelector` field.
- [ ] There aren't two sidecars in the same namespace without `workloadSelector`.
- [ ] Global Sidecar (placed in root Namespace) should not have `workloadSelector`
- [ ] IstioEgressListener `hosts` field to ensure access to istio-system services (for both telemetry and policy services)
- [ ] IstioEgressLister `hosts` have to be in namespace/dnsName format.
- [ ] IstioEgressListener `bind` must have format: x.x.x.x or unix:///path/to/uds or unix://@foobar
- [ ] IstioIngressListener `bind` must have  `x.x.x.x` format.

**Comment by xeviknal** [comment]
All validations in the list are finished. Closing the issue.
