### ISSUE TITLE
Kiali video tutorials for Istio tasks

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1582]
The Istio website documents all the tasks that you can perform with Istio and provides an example on how to accomplish that task. This makes it easy for people who are new to Istio to follow along and learn how to use it and its capabilities.

Right now these tasks are all done using yaml and the CLI. We should see how to update these tasks to use Kiali instead.

This epic will track the videos to produce and any other associated tasks.  Note that each video should have its own "epic subtask" issue.  Videos do not necessarily need to be recorded only by the epic assignee.

Kiali Youtube channel: https://www.youtube.com/channel/UCcm2NzDN_UCZKk2yYmOpc5w

- [x] Add latest videos section to kiali.io #2274 
- [x] Install Istio and Kiali on Minikube 
- [x] Install Bookinfo sample
- [x] Setting up UI development environment w/ backend proxy w/ tips+tricks
- [ ] Setup routing to split traffic
- [ ] Routing based on request headers
- [ ] Configure Gateways Ingress/Egress 

Add more as needed...

**Comment by mtho11** [comment]
@jshaughn and talked about a 'Kiali by Example' page on kiali.io that would contain short 1-3 minute videos (not to exceed 5 minutes) following the above examples and the [Istio.io Tasks](https://istio.io/docs/tasks/). 

BTW: I liked the way http://istiobyexample.dev did it.

**Comment by lucasponce** [comment]
@mtho11 I'm actively working on Wizards so probably your feedback from this task can help us to identify if there is something missing in our current implementation and next work.

Let me know and happy to help here, as well.

**Comment by abonas** [comment]
why is this labeled as backlog if this is part of spring 35?

**Comment by jshaughn** [comment]
@abonas Actually, I think that's normal.  We don't [currently] remove the backlog label when a backlog item moves to the sprint.  It just becomes part if the sprint backlog.

**Comment by jshaughn** [comment]
@mtho11 So how should we handle this issue?  I know you have created several videos already.  Should we close this?  Or, if you feel more videos should be done on a continuous basis we could turn this into an epic and start making each video a subtask.  If you want to do that please add the epic label and also list out the known video subtasks.  Also, it would seem that if we are going to put effort into videos we should maybe also do #2274?   Let me know...

**Comment by mtho11** [comment]
At this point, I want to publish one video a week (or thereabout: 1 ~3). Something very specific and short like < 2 minutes (hopefully) and we can tweet that as well. #2274 is vital to this effort to get the proper visibility.

**Comment by mtho11** [comment]
@jshaughn note that #2274 is not included in this sprint yet and I believe it should be.

**Comment by abonas** [comment]
@mtho11  your tutorials are great. 
What tutorials are planned for this sprint? I wasn't sure I understand looking at this GH issue. 
thanks

**Comment by mtho11** [comment]
@abonas yes, we need to decide and prioritize that.

**Comment by jshaughn** [comment]
@lucasponce unassigning @mtho11 , do we want to close this epic in lieu of the tutorial work?
