### ISSUE TITLE
Upgrade to Patternfly 4 (pf.next)

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1588]
Epic issue to migrate Kiali UI into PatternFly 4 framework:
https://github.com/patternfly/patternfly-next
http://patternfly-react.surge.sh/patternfly-4/index.html

JIRA:
https://issues.jboss.org/browse/KIALI-2088

Tasks:
- [x] [PF4] Move Initial adoption components
- [x] [PF4] Namespace Selector
- [x] [PF4] Jaeger Integration with Kiali
- [x] [PF4] Jaeger Toolbar expand advanced options component https://github.com/kiali/kiali/issues/1665
- [x] [PF4] Service Metrics
- [x] [PF4] App Page
- [x] [PF4] Login page - error massage has a 'danger' literal at the end of the sentence
- [x] [PF4] Upgrade patternfly/react-core to 3.2.6 stable
- [x] Upgrade PF4 to release 3.58.1
- [x] [PF4] Restore Kiali colors
- [x] [PF4] Charts from K-charted
- [x] [PF4] Migrate Breadcrumb
- [x] Migrate Tabs from details pages
- [x] [PF4] Charts for Overview cards
- [x] Upgrade patternfly/react-core to 3.87.3 stable
- [x] [PF4] Move filters to PF4
- [x] [PF4] Move Overview Cards and Links
- [x] [PF4] Move DurationDropdownContainer
- [x] Fix warnings in details view app and workloads
- [x] [PF4] Service Details #1591
- [x] [PF4] Workload Page #1592
- [x] [PF4] Istio Page #1593
- [x] [PF4] Overview Page #1594
- [x] [PF4] Kiali Wizards #1595
- [x] UI - Move lists to virtual scrolls #1596
- [x] [PF4] Move Refresher #1598
- [x] [PF4] Move Overview Toolbar #1599
- [x] [PF4] Move ToolbarDropdown #1601
- [X] [PF4] Migrate the cytoscape graph toolbar #1606 
- [x] [PF4] Migrate validation icons, tooltips, popovers, etc. #1635
- [x] [PF4] Migrate Labels #1634 
- [x] [PF4] Migrate MTLS status in header/overview https://github.com/kiali/kiali/issues/1735
- [x] [PF4] Find alternative to current tooltips in charts #1702 
- [x] [PF4] Move icon of validation to CheckCircle like MockUP #1719
- [x] [PF4] Migrate HealthIndicator https://github.com/kiali/kiali-ui/pull/1475
- [x] [PF4] Move Label component #1723 
- [x] [PF4] Migrate Graph filter display options #1746 
- [x] [PF4] Migrate charts from the graph sidebar #1747 
- [x] [PF4] Move MissingIstioSideCar component #1799
- [x] [PF4] Move Spinner #1802
- [x] [PF4] Service Page #1590 
- [x] Move Refresher to UX design #1724
- [x] [PF4] Migrate from Overpass Font to Red Hat Font #1771
- [x] [PF4] Migrate side-panel StackBarCharts #1787
- [x] [PF4] Migrate NotificationDrawer #1639 
- [x] [PF4] Migrate the graph filter toolbar #1607
- [x] [PF4] Migrate the graph sidebar #1608
- [x] [PF4] Create background in grey color like design for all views #1600
- [x] [PF4] Migrate Traffic Tabs #1808
- [x] [PF4] PF4: migrate namespace selection dropdown #1790 
- [x] [PF4] Consolidate PF4 Icons #1813
- [x] [PF4] Replace All Occurrances of Icon (PF3) with KilaiIcon #1825 
- [x] Move toast notification of ServiceInfo #1882 

## issues PF4 to follow

- [x] Investigate / improve pf4 charts tooltip https://github.com/kiali/kiali/issues/1792

## After migration
- [x] Remove PF3 #1857 
- [ ] Adopt RCUE in PF4 and remove patternfly library  #1949
- [ ] Clean styles after PF4 migration #1950

**Comment by lucasponce** [comment]
I will close this issue.
Migration to PF4 is done.
There are a couple of side tasks related to adjust old styles that are not part of the migration itself but those can be considered on-going UI tasks.
