### ISSUE TITLE
[multi-cluster] Enhance support for mesh deployment models

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#1833]
This work is now targeting a minimum of Istio 1.8.  With 1.8 istio is revising and formalizing its deployment models from "shared" vs "replicated" control planes, to a more rich and flexible approach using a single model, based on building blocks such as mesh, network, cluster, control plane, data plane, namespace, and service.

See [Deployment-models](https://preliminary.istio.io/latest/docs/ops/deployment/deployment-models/).

This Epic is for work that improves the Kiali experience when working with a single mesh, whether it employs multiple clusters, control planes, and/or data planes.  By "single mesh" we use the definition provided by Istio: in a single mesh a service must be unique within a namespace.

In scope for this Epic are answers and impls for:
- How to gather mesh topology.
- How to visualize mesh topology.
- How to deploy Kiali given an Istio mesh deployment Model.
- How to "link" Kiali deployments when the deployment model involves multiple Kiali installations.
- How to incorporate mesh topology into our existing pages/features/API.
  - How to visualize cross-cluster traffic in the graph
  - other?

In general a non-basic deployment model will incorporate multiple [k8s] clusters.  The multi-cluster deployment options are [described here](https://preliminary.istio.io/latest/docs/setup/install/multicluster/).

Related issues:
#3409 Find/resolve the clusters available to a certain control plane
#3335 Kiali support for single prometheus with "clusterID" discrimination

Sub-Tasks: (Note that active sub-tasks are currently WIP/Exploratory/Research oriented)

- How to gather mesh topology.
  - [x] gather meshId https://github.com/kiali/kiali/issues/3592
  - [x] gather cluster information https://github.com/kiali/kiali/pull/3413 https://github.com/kiali/kiali/issues/3592
  - [ ] gather exposed namespace/service information
  - [ ] ...
- [ ] How to visualize mesh topology.
  - [x] List view https://github.com/kiali/kiali-ui/pull/2000 https://github.com/kiali/kiali/issues/3592
  - [x] Graph view https://github.com/kiali/kiali/issues/3592
  - [ ] ...
- How to deploy Kiali given an Istio mesh deployment Model.
  - [ ] kiali.io documentation about Kiali deployment model
  - [ ] ...
- How to "link" Kiali deployments when the deployment model involves multiple Kiali installations.
  - [ ] Discover Kiali instances in remote clusters #3718, #3526
  - [ ] ...
- How to incorporate mesh topology into our existing pages and API.
  - [ ] How to visualize cross-cluster traffic.
    - [x] Make initial use of *_cluster_name metric attributes https://github.com/kiali/kiali/issues/3439 https://github.com/kiali/kiali/issues/3592
    - [x] Use home cluster for idle nodes and service nodes (see https://github.com/kiali/kiali/pull/3511#discussion_r538896993 and https://github.com/kiali/kiali/pull/3511#discussion_r538900396) https://github.com/kiali/kiali/issues/3592
    - [x] Side-panel support for cluster and namespace boxes https://github.com/kiali/kiali/issues/3545 https://github.com/kiali/kiali/issues/3592
    - [ ] Navigation across Kiali pages #3717
  - [ ] ...

Original Epic description below:
====================

Istio supports a multi-cluster setup with isolated networks. Setup is described at https://istio.io/docs/setup/install/multicluster/shared-gateways/

In this setup, there is a **main** cluster. The other clusters are **secondary** clusters. The **main** cluster in the one with a complete Istio installation. Secondary clusters have only istio-ingressgateway, istio-citadel and istio-sidecar-injector.

Apparently, the istio-ingressgateways are entry points for cross-cluster traffic of the mesh; i.e. if one workload wants to send traffic to a service in a remote cluster, the sidecar of the workload connects to the istio-ingressgateway of the remote cluster and pushes traffic through that connection. This applies to all data of the mesh, including Istio's infrastructure data (there are special ports in ingress to receive telemetry, traces, envoy data, etc.). 

Currently, under this setup, Kiali can only be installed in the **main** cluster. In the secondary clusters, prometheus, jaeger, and even Istio's CRDs are not accessible or not available, so Kiali won't work. Once Kiali is installed in the _main_ cluster, it works without errors but with issues. Most issues seem to be related to the fact that Kiali is blind to whatever is happening in the remote cluster.

Here is the list of issues to be addressed to add support for the multi-cluster setup (multi-network):

- [ ] List namespaces living in remote clusters that are part of the mesh.
  - Currently, Kiali's shared namespace dropdown and the overview page list only namespaces on the _main_ cluster (or the cluster where it's installed). Kiali should also list namespaces of remote clusters containing workloads that are part of the mesh.
- In the overview page:
  - [ ] Count all services / workloads / apps in the overview page.
    - The overview page shows the number of svcs/apps/workloads. The overview page, sometimes, doesn't enumerate all objects and shows a number that is less than the real number of objects.
  - [ ] Enhance health checks to validate objects in remote clusters.
- [ ] Fully graph the service mesh
  - Although all required metrics to graph the mesh are stored in prometheus, Kiali truncates the graph to only workloads/apps/services that are present on the _main_ cluster.
  - Drilled-down graph is partially affected. Behavior is not consistent. Sometimes nodes are shown, some other times they get hidden.
- [ ] List applications that are present in remote clusters in the apps list page.
  - Apps that are only created in remote clusters are not shown in the apps list page, but they belong to the mesh and metrics are correctly reported.
  - [ ] Enhance health checks to validate objects in remote clusters.
- In the application page:
  - [ ] List workloads living in remote clusters.
  - [ ] List services living in remote clusters.
  - [ ] Enhance health checks to validate objects in remote clusters.
  - [ ] Enhance the traffic tab to work with multi-cluster. (Although, since this relies on graph endpoints, it may get solved with graph work.)
  - [ ] Enhance metrics tabs to work with multi-cluster setup. (Because the Metrics settings dropdown shows "unknown" for apps/versions of remote objects).
- [ ] List workloads that are present in remote clusters in the workloads list page.
  - [ ] Enhance health checks to validate objects in remote clusters.
- In the workload page:
  - [ ] Enhance the page to fetch remote workload details.
    - [ ] Enhance to fetch list of matching remote pods.
    - [ ] Enhance to fetch list of matching remote service objects.
  - [ ] Enhance health checks to validate objects in remote clusters.
  - [ ] Enhance the traffic tab to work with multi-cluster.
  - [ ] Enhance metrics tabs to work with multi-cluster setup. 
  - [ ] Enhance logs tab to fetch logs from the remote pods and containers.
- [ ] List services that are present in remote cluster in the services list page.
  - [ ] Enhance health checks to validate objects in remote clusters.
- In the service page:
  - [ ] Enhance the page to list which clusters have the service created.
  - [ ] Enhance the page to list details of each service in each cluster.
  - [ ] Enhance the page to list endpoints on each cluster.
  - [ ] Enhance the page to list matching workloads on each cluster.
  - [ ] Enhance the page to list the combined list of workloads of all clusters.
  - [ ] Enhance the traffic tab to work with multi-cluster.
  - [ ] Enhance metrics tabs to work with multi-cluster setup. 
- [ ] Extend validations to work with multi-cluster.
  - Some validations use the cluster API to fetch some resources. Some of those resources may not be available in the _main_ cluster and will raise false positives.
- ...and anything else that arises.

**Comment by israel-hdez** [comment]
Removing this from the sprint and marking as "future", because there is still no clear direction on multi-cluster support.
Istio's implementation is provided "as is", but subject to change.

**Comment by uc-dang-tiki** [comment]
How about istio multi cluster shared network with SINGLE NETWORK. Kiali cannot see workload, service of other cluster (except cluster which installed kiali), and cannot see http metric of workloads

**Comment by israel-hdez** [comment]
Hi, @uc-dang-tiki 
We didn't do the analysis for single-network setup. This is the reason there is no dedicated issue for that case. But it may have similar issues as the ones commented here.

Most likely, when we start addressing the multi-network case, we will also take into account the single network case. So, you could up-vote this issue if you are interested in this support.

**Comment by djamaile** [comment]
So if I understand this correctly. I have two clusters and both have istio installed. Kiali can only work on one cluster? (showing graph data etc. on one cluster)

**Comment by israel-hdez** [comment]
@djamaile If Istio is installed in both clusters, you probably are talking about the replicated control plane scenario for which Kiali has basic support. Related issue is https://github.com/kiali/kiali/issues/1363.

Also see the very short doc section: https://kiali.io/documentation/features/#_multi_cluster_support

**Comment by djamaile** [comment]
@israel-hdez yes, looks good! Thanks

**Comment by jshaughn** [comment]
@israel-hdez I am re-opening this as IStio MC support seems to be getting revisited, starting with the revisions [in this 1.8 draft document](https://docs.google.com/document/d/1EZeTaoFb--Rr4EpJsjMBnRtm1VZT14mJpRbPJiJh37M/edit#heading=h.unrky8u5qn5h).

**Comment by djamaile** [comment]
Hi @jshaughn the docs are locked. It is possible for me to look at them? I am still very interested in this.

**Comment by lucasponce** [comment]
I think this Epic was good when it was created and it helped to start the PoC of multicluster features.

But probably from https://github.com/kiali/kiali/discussions/4081 we will need a better definition of Epic(s) (to be discussed).

So, I'm inclined to close this one in favor to a new re-definition of the scope based on the below discussion.

**Comment by jshaughn** [comment]
I'm OK with closing this one, it is pretty huge and I think we will do better to work from the current discussion and develop more refined epics, using this as a reference when necessary.
