### ISSUE TITLE
Research Iter8 integration with Kiali

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#2007]
Iter8 project https://iter8.tools/ provide automatic canary deployment features and it shares some synergies with Kiali use cases like described in https://medium.com/kialiproject/kiali-observability-in-action-for-istio-service-mesh-69127f792103

This issue is defined as a research task about potential next steps about how Kiali could integrate some operations and reporting linked with Iter8 scenario.

Subtasks:
- [x] Enable Kiali to create and manipulate iter8 experiments https://github.com/kiali/kiali/issues/2454
- [x] Enable Kiali to visualize iter8 experiments https://github.com/kiali/kiali/issues/2453
- [x] Enable refresh control in Iter8 list page https://github.com/kiali/kiali/issues/2628
- [ ] Create Iter8 experiments as a Service details Wizard https://github.com/kiali/kiali/issues/2629
- [x] Integrate Iter8 generated Istio Config inside Kiali Wizards https://github.com/kiali/kiali/issues/2630
- [x] Enhance Iter8 details page https://github.com/kiali/kiali/issues/2633
- [x] Improve baseline/candidate representation in Iter8 list page https://github.com/kiali/kiali/issues/2634
- [x] Add more examples under demos repo to be used for Iter8 integration https://github.com/kiali/kiali/issues/3235

**Comment by kalantar** [comment]
I’m going to document some initial thoughts (developed together with @fabolive @sriumcp @kimikowang and @sushmarchandran). There is lots about the extensibility of Kiali that we do not understand so many statements are a bit speculative. Please help give shape to the right path forward.

Looking at https://medium.com/kialiproject/kiali-observability-in-action-for-istio-service-mesh-69127f792103, a manual a/b or canary test is documented. Using this as a starting point, we have identified three use canary use cases: (a) Manual (b) Automated and (c) User-Assisted Feedback on the use cases might be the best first step; then more technically on the integration with Kiali.

**Comment by kalantar** [comment]
**(a) Manual**
The flow for a manual canary test is similar to the blog article. I’ve highlighted concepts we’ve added from iter8.

- User deploys a new version of a service
- Using Kiali, the user can inspect metrics [1] (on Service > Inbound Metrics)
- Using Kiali, the user can inspect/update/add success criterion [2] (new function)
- Using Kiali, the user can change the routing. If there are success criteria defined, the _Update Weighted Routing_ dialog can be augmented with a “set to recommended weights” widget
- User can repeat until finally choosing one to receive 100% of the traffic.
- User deletes unused version of service


[1] Is there a way to add new metrics in Kiali? In iter8 metrics are (currently) defined via prometheus queries. In theory this can be extended to include other sources of metrics. If we were to define a new metric, would there be a way to visualize its in Kiali along with the existing graphs? If possible, the use cases can be extended to allow users to add/update metrics. The iter8 analytics engine can provide text statements/summaries of the metrics as well. Statements like “with 90% confidence, the latency is less that 0.1s” There are many such statements possible and some thought on what would be useful is necessary. A location to show these to the user would need to be considered. On the graph?  On s separate metrics management tab?

[2] success citeria are service/deployment specific requirements computed over the set of metrics. Initially it may be enough to read them from the namespace where service is deployed. However, a means to see and manage (add/edit/delete) success criteria will eventually be necessary. Perhaps on a new service tab. The iter8 analytics engine can provide text statements/summaries of the criteria that could be displayed on such a tab. Other ways to understand and visualize the success criteria should be explored.

**Comment by kalantar** [comment]
**(b) Automated**
The flow for an automated canary test is similar but adds ability to start an automated rollout:
- User deploys a new version of a service
- Using Kiali, the user can inspect metrics (on Service > Inbound Metrics)
- Using Kiali, the user can inspect/update/add success criterion (new function)
- Using Kiali, the user can change the routing. 
- User can start an automated rollout from current routing (new service action) [3]
- User can force rollout to completion (success) or failure (rollback) (also new service actions?)
- [iter8 deletes the unused version]

[3] To start an automated rollout a new dialog to collect/validate version/timing/criteria information is needed. When an automated rollout is in progress the ability to modify the routing rules should be disabled. There should be a way to visualize the progress of an experiment (Progress bar? dial? Graph showing current routing over time?). Also history of iter8 experiments may be present. How should they be managed?

**Comment by kalantar** [comment]
**(c) User-Assisted**
The idea of the user-assisted use case is that the user would start a “user assisted” rollout instead of an “automatic” rollout. In this case, when iter8 determines that it is time to change the routing, it sends a notification to the user (via Kiali) and pauses evaluation. The user would need to explicitly take an action like “proceed”, “retry iteration”, “rollback” or “rollforward” to trigger progress. Need to determine how to present these choices. An experiment tab? From the notification itself?

**Comment by jshaughn** [comment]
We need to get together and talk about each option.  My personal preference is to see the Kiali UI extended with new, dedicated interface for running automated canary tests/deployments.  We can likely leverage and link to existing parts of the UI to assist, like the graph and detail views.  A strong offering for this important use case would be a powerful addition to Kiali's configuration abilities.  New backend API support would be added as needed.

**Comment by lucasponce** [comment]
Some comments inline:


> **(a) Manual**
> The flow for a manual canary test is similar to the blog article. I’ve highlighted concepts we’ve added from iter8.
> 
> * User deploys a new version of a service
> * Using Kiali, the user can inspect metrics [1] (on Service > Inbound Metrics)
> * Using Kiali, the user can inspect/update/add success criterion [2] (new function)
> * Using Kiali, the user can change the routing. If there are success criteria defined, the _Update Weighted Routing_ dialog can be augmented with a “set to recommended weights” widget
> * User can repeat until finally choosing one to receive 100% of the traffic.
> * User deletes unused version of service
> 
> [1] Is there a way to add new metrics in Kiali? In iter8 metrics are (currently) defined via prometheus queries. In theory this can be extended to include other sources of metrics. If we were to define a new metric, would there be a way to visualize its in Kiali along with the existing graphs? If possible, the use cases can be extended to allow users to add/update metrics. The iter8 analytics engine can provide text statements/summaries of the metrics as well. Statements like “with 90% confidence, the latency is less that 0.1s” There are many such statements possible and some thought on what would be useful is necessary. A location to show these to the user would need to be considered. On the graph? On s separate metrics management tab?

Kiali allows to add custom tabs for metrics. This feature was originally used to provide additional metrics about the "Runtimes" inside a Pod (i.e. Java server, Go, Node), but I think that a new tab with specific metrics for "Iter8" domain can be a start point.

> 
> [2] success citeria are service/deployment specific requirements computed over the set of metrics. Initially it may be enough to read them from the namespace where service is deployed. However, a means to see and manage (add/edit/delete) success criteria will eventually be necessary. Perhaps on a new service tab. The iter8 analytics engine can provide text statements/summaries of the criteria that could be displayed on such a tab. Other ways to understand and visualize the success criteria should be explored.

Where does this make sense to be linked ? For example, today, "Service" is the concept where we link the extension with the API Management (3scale). 
The success criteria is something defined at "Service" level by default, or it's normal to be defined at "namespace" level ?
If "Success Criteria" is a strong separated entity where it can be applied a pattern list > detail, it can also be a good idea to enable a specific main entry menu below "Istio Config" to access to those.


---


> **(b) Automated**
> The flow for an automated canary test is similar but adds ability to start an automated rollout:
> 
> * User deploys a new version of a service
> * Using Kiali, the user can inspect metrics (on Service > Inbound Metrics)
> * Using Kiali, the user can inspect/update/add success criterion (new function)
> * Using Kiali, the user can change the routing.
> * User can start an automated rollout from current routing (new service action) [3]
> * User can force rollout to completion (success) or failure (rollback) (also new service actions?)
> * [iter8 deletes the unused version]
> 
> [3] To start an automated rollout a new dialog to collect/validate version/timing/criteria information is needed. When an automated rollout is in progress the ability to modify the routing rules should be disabled. There should be a way to visualize the progress of an experiment (Progress bar? dial? Graph showing current routing over time?). Also history of iter8 experiments may be present. How should they be managed?

Experiments are defined per Service level ? Or those can be generic ?
The "progress" or lifecycle of an experiment is managed directly on an "Experiment" entity or is it necessary to pull several sources (metrics, iter8 definitions, k8s definitions) to calculate the progress ?


---


> **(c) User-Assisted**
> The idea of the user-assisted use case is that the user would start a “user assisted” rollout instead of an “automatic” rollout. In this case, when iter8 determines that it is time to change the routing, it sends a notification to the user (via Kiali) and pauses evaluation. The user would need to explicitly take an action like “proceed”, “retry iteration”, “rollback” or “rollforward” to trigger progress. Need to determine how to present these choices. An experiment tab? From the notification itself?

It seems that perhaps a main entry for "Iter8" where all "Experiments" entity may be needed, and probably there can be located all specific actions for the domain.
And also it makes sense that under the "Service Details" some contextual actions can be augmented into existing Wizards or even create a specific wizard for it.


---

As a first feedback I can say that I understand the high level scenarios and how a preliminar fit can be done in Kiali.
Perhaps it can be good if we prepare some mockups to continue discussion and put together a working session where we can discuss it.

Also, today we have one extension in Kiali (with 3scale API Management) technology that was coded without a strong structure.
Now with iter8 we need to put a more robust way to config an extension, and define which structures in backend/frontend can use, to help others to work on it.
About this there are already some planned work for current Sprint but probably it will be necessary more steps.

But anyway, let's continue discussing and adding comments about it, I think we can iterate more in the high level flows and in the requeriments to put together this technology in Kiali.

**Comment by jshaughn** [comment]
I'm not sure about this being an extension under some existing entity but maybe it fits under service.  I think we may want to consider a new menu item specifically for "Canary Deployments/Itr8").  A location to consolidate automated canary deployments/experiments.

**Comment by lucasponce** [comment]
I think I see two things here:
- Specific entities (on this iter8 extension) - like Experiments - deserves a new menu item ("Canary Deployments/Iter8" sounds correct). Under this menu list/CRUD/specific domain actions on those entities are located.
- Another thing is where to link these actions, then probably as we have today, some actions can be available under Service details.

Note that in the #2146 is basically the same pattern I guess we should follow, specific actions should have their menu item for better delimitation, but also there can be some actions located in other places (i.e. under the Service details, "link this service with this Experiment").

I will use #2146 as the foundation to better structure this, in order that can standarize/simplify these flows.

**Comment by kimikowang** [comment]
Hi @lucasponce , thanks for your comments! Regarding some of your questions in the thread:
> > [2] success citeria are service/deployment specific requirements computed over the set of metrics. Initially it may be enough to read them from the namespace where service is deployed. However, a means to see and manage (add/edit/delete) success criteria will eventually be necessary. Perhaps on a new service tab. The iter8 analytics engine can provide text statements/summaries of the criteria that could be displayed on such a tab. Other ways to understand and visualize the success criteria should be explored.
> 
> Where does this make sense to be linked ? For example, today, "Service" is the concept where we link the extension with the API Management (3scale).
> The success criteria is something defined at "Service" level by default, or it's normal to be defined at "namespace" level ?
> If "Success Criteria" is a strong separated entity where it can be applied a pattern list > detail, it can also be a good idea to enable a specific main entry menu below "Istio Config" to access to those.
> 

Yes "Success Criteria" is defined at "Service" level, or more precisely, at the level of an "Experiment" for one service. It determines whether an experiment(e.g. a canary rollout) should be considered as a success or not. A SuccessCriteria object can be linked by multiple Experiment instances.

> > **(b) Automated**
> > The flow for an automated canary test is similar but adds ability to start an automated rollout:
> > 
> > * User deploys a new version of a service
> > * Using Kiali, the user can inspect metrics (on Service > Inbound Metrics)
> > * Using Kiali, the user can inspect/update/add success criterion (new function)
> > * Using Kiali, the user can change the routing.
> > * User can start an automated rollout from current routing (new service action) [3]
> > * User can force rollout to completion (success) or failure (rollback) (also new service actions?)
> > * [iter8 deletes the unused version]
> > 
> > [3] To start an automated rollout a new dialog to collect/validate version/timing/criteria information is needed. When an automated rollout is in progress the ability to modify the routing rules should be disabled. There should be a way to visualize the progress of an experiment (Progress bar? dial? Graph showing current routing over time?). Also history of iter8 experiments may be present. How should they be managed?
> 
> Experiments are defined per Service level ? Or those can be generic ?
> The "progress" or lifecycle of an experiment is managed directly on an "Experiment" entity or is it necessary to pull several sources (metrics, iter8 definitions, k8s definitions) to calculate the progress ?
> 

Yes Experiment is defined per service. Specifications and Status of an experiment are recorded in an Experiment object(k8s cr instance). The `iter8 controller` manages the progress of an experiment by iteratively reading responses from the `iter8 analytics` engine, and updates the status in the CR instance.

**Comment by kalantar** [comment]
I see several times the expression that it would make sense to have a top level "iter8" entity to capture all the canary deployments for all the services in a cluster. I agree with this. Mostly because I think the notion of a canary deployment is sufficiently interesting to warrant it. Many of the concepts (experiment and success criteria) are service specific @kimikowang described. I wondered therefore if it makes sense for these to visible in the context of a service entity as well. agree that some mockups would help us explore this better. Will work on some.

**Comment by lucasponce** [comment]
Just to update and consolidate this effort.
Extensions guideline are ready in Kiali master and documented:
https://kiali.io/documentation/extensions/

Also we some informal notes to help to jump coding them in the Kiali repos:
https://gist.github.com/lucasponce/263c778e567148bae8585159ac5599c4

**Comment by lucasponce** [comment]
Hi @kimikowang @kalantar @jadeyliu939 @fabolive,
I moved this issue to an epic just to update it and reflect that it will involve multiple subtasks.
Also, I'd like to add an iter8 membes group in kiali, to simplify notifications (let me know which IDs you want me to put there).

I added myself as assigned to this epic to help you with any topic related this, I will coordinate the effort and pull other members to review/participate in the extension.

Let us know if you need anything from our side.

Thanks.

**Comment by fabolive** [comment]
Hi @lucasponce. You can add the ids above for now. Thanks!

**Comment by fabolive** [comment]
@lucasponce, @jadeyliu939: I created issues #2453 and #2454 as subtasks of this epic.

**Comment by lucasponce** [comment]
Thanks @fabolive. I've added them subtasks in the first comment on this way we can also to see them in the global project Sprint:
https://github.com/orgs/kiali/projects/9

Also, we can use the tasks as a method to show progress, if you think #2453 and #2454 can also contain different steps, we can add some tasks just to track status.

In the Kiali project there are several examples that can be used as templates, but in case of doubts, just ping me and I'll help.

Thanks !
Lucas

**Comment by lucasponce** [comment]
@fabolive @jadeyliu939 
cc @kiali/iter8 

I've closed the first 2 subtasks for this epic but I will keep it open the epic to add more tasks to:
- Track the refinements @jadeyliu939 is working on in the iter8 details page.
- Discuss/comment more actions/changes, i.e. Experiment creation can be better integrated at service level.

So, I will move this EPIC to our next Sprint and I will update it with more subtasks after syncing with you.

**Comment by fabolive** [comment]
Sounds good, @lucasponce. Let's discuss this in our meeting tomorrow.

**Comment by lucasponce** [comment]
@fabolive @jadeyliu939 
cc @kiali/iter8 

As commented yesterday, I've added more substasks related the effort to enhance/improve the integration of Iter8 in Kiali.

The goal is basically to split the effort in subtasks that may help us to clarify us the feature (by "feature" I mean here to define information to be displayed, actions to be performed on the entities, and potential relation/integration with other Kiali areas), also in a granularity level that can be easy to handle (to avoid big PRs or big single efforts in one step).

When feature are more clear, then next step is to start involving our colleagues from UX to help us to review/define the user experience, and then with a more detailed feature they can help us to refine our proposal or provide us additional mockups.

My goal is to use these issues to discuss about it and coordinate, feel free to jump on them adding comments and ideas.

P.S.: Note that in some European cities we will afk until next Monday/Tuesday, my responses will be delayed until next week.

Thanks.

**Comment by lucasponce** [comment]
As part of the follow up tasks we will target to update Kiali with Iter8 1.x versions and continue progressing with the integration in details pages, metrics and wizards.
