### ISSUE TITLE
Reorganize documentation for kiali.io

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#2181]
Today Kiali holds documentation for kiali.io in a separate repo and it presents some challenges:

- Hard to maintain a documentation updated when there are changes on the features.
- Impossible to track which feature is included in which version, there is a de-facto, it refers to "latest".

These two issues are serious and make difficult for everyone to contribute in an efficient way to doc.

So, this issue proposes an EPIC to define:

- How documentation content can be separated from the html template and hosted together with the code.
- With that in mind, in the same PR where a modification is done, reviewer can ask to modify the content of the documentation, without wait to open a new issue and update a separate task (that in practice, it happens very few times and badly).
- Also, as a side effect, when Kiali performs a release, content is versioned too, and it would be simplified how to track documentation in a better way.

It's clear that this affects in how site is built but I think is worth to put priority on this.

- [x] Versioned content
- [x] Add section for security notifications https://github.com/kiali/kiali/issues/2536
- [x] Add section for release information [notes, changes, etc] https://github.com/kiali/kiali/issues/2536
- [x] Investigate Google Season of Docs https://github.com/kiali/kiali/issues/2619

**Comment by jotak** [comment]
I have a comment about config documentation: currently, we just point to Kiali CR (ex: https://github.com/kiali/kiali/blob/c78f195fcbe214e56a918d616ed2f241be24c968/operator/deploy/kiali/kiali_cr.yaml#L433-L470 ) when we want to refer to configuration. I see two problems with that:

- This is not pretty. I think people could expect more than just yaml comments
- We can either link to `master` (latest) or to a specific commit (like the link I put above). Both are problematic: links to master can be inaccurate if we put anchors to specific lines, when master changes ; and links to commits wouldn't show the most up-to-date content.

So, as part of this task, I think it would be nice if we could start thinking about having a better documented configuration, integrated into kiali.io.

**Comment by jshaughn** [comment]
This is an RH internal link, but is an [internal review of the web site](https://docs.google.com/document/d/1KrGbE9rW_XA9Ph9pDNMajinQ2L9ZjVqCc44PwCZCCWA/edit?ts=5e1dcbfd#heading=h.l1s9y5ya55qe).

**Comment by aljesusg** [comment]
I started the poc about versions in https://github.com/kiali/kiali.io/pull/142 so time ago but I moved it by other tasks I can resume this one
