### ISSUE TITLE
Make Kiali working better with Kafka

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2197]
Today there's a couple of problems when we try to see Kafka-based microservices in Kiali (and we could probably generalize to event-based microservices). We could try to make it frictionless.

In this task I'll try to group several issues, that we can eventually handle via subtasks:

- [x] Quite often, Kafka brokers are deployed as a StatefulSet. Because of that, Kiali won't recognize the workload out of the box: StafefulSet fetching needs to be explicitly enabled in config. Maybe we could look for a solution to make it work more easily. #2253 

- [x] I've noticed several inconsistencies in the graph, for instance, where an edge is showing metrics whereas the related source workload did not: https://github.com/kiali/kiali/issues/2498

- [x] Kafka deployment makes use of headless service, which might be hidden in Kiali graph. There's already an issue about that: https://github.com/kiali/kiali/issues/976

- [x] Kafka, like any other TCP/non-HTTP-based service, generates istio TCP metrics and no HTTP metrics. In the metrics screen they appear at the bottom and we need to scroll down to them. UX-wise, we could help a little bit, for instance by reducing the size of "no-data" charts (or even hide them?) #2495

- [x] Show metrics to service entries in summary panel: https://github.com/kiali/kiali/issues/2497

- [x] (Minor) Traffic animation could be improved in TCP scenarios such as Kafka ones: https://github.com/kiali/kiali/issues/2469

- [ ] Investigate Kafka metrics / dashboard
( https://medium.com/@adam.kotwasinski/deploying-envoy-and-kafka-8aa7513ec0a0 )

- [ ] Last but not least, the istio graph is not so much interesting with Kafka, because all communications are passing through the kafka broker, hence hiding the publisher-subscriber relationships. We could try to fix that. But is has _many_ implications (discussions would be needed for that).

**Comment by jotak** [comment]
Small remark: Envoy's PRs to start handling kafka protocol was merged in Envoy 1.13 and 1.14 , which _seem_ to be in Istio 1.5. So when this filter is active it should provide additional telemetry, hence allow for specific dashboards.

**Comment by jotak** [comment]
Three scenarios identified that we should take care of:

* S1: Kafka clients & Kafka are all in mesh. This case seems to work pretty well with the graph already.

* S2: Kafka clients only are in mesh, Kafka itself is in a different namespace, with Service Entry defined [1]. Graph is correct, only drawback is that the summary panel doesn't show metrics to service entry. Need to investigate if there's a valid reason for that, because metrics actually exist to SE's hosts. Perhaps a specific prom query needs to be forged for this case.

* S3: Kafka clients only are in mesh, Kafka itself is in a different namespace. Istio outbound traffic policy set to permissive. In this situation it seems that Kiali doesn't display edges to headless services (ie. kafka broker). To be confirmed.

**Comment by jotak** [comment]
For anyone who'd like to try/test some Kafka scenario here, I've cleaned up a little bit the demo I use and written a quick startup doc: https://github.com/ia3andy/game-of-stacks/blob/master/ISTIO-QUICK-START.md

It works on minikube, but should work on other targets too. It deploys Kafka (via Strimzi), Istio and a couple of microservices that will produce & consume kafka messages.
