### ISSUE TITLE
Config validation for Istio Security objects

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#2227]
Increase coverage of validation on Security objects:

- [x] Add validations for AuthorizationPolicy objects https://github.com/kiali/kiali/issues/2081
- [x] Add validation to Sidecar https://github.com/kiali/kiali/issues/1541
- [x] Add validations for PeerAuthentication Object https://github.com/kiali/kiali/issues/2086
- [x] Add validation to ServiceRole https://github.com/kiali/kiali/issues/1506
