### ISSUE TITLE
Support creation of Istio Security objects from Kiali

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#2231]
This is an EPIC issue to track how to improve the existing Wizards and adding new ones to cover Istio security use cases.

Some issues related:
- [x] Add UI to apply AuthorizationPolicy https://github.com/kiali/kiali/issues/2041
- [x] Check if RBAC objects are fully deprecated or there are some valid use cases around https://github.com/kiali/kiali/issues/1497
- [x] Review existing wizards and add Policy objects when mTLS is involved https://github.com/kiali/kiali/issues/1381
- [x] Add support to PeerAuthentication resource https://github.com/kiali/kiali/issues/2520
- [x] Add support to RequestAuthentication https://github.com/kiali/kiali/issues/2737
- [x] Add UI to apply PeerAuthentication and RequestAuthentication https://github.com/kiali/kiali/issues/2797
