### ISSUE TITLE
Improve visualization, filtering and searching in Kiali Logs tab

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#2232]
Kiali provides a basic logs tab per workload, but it has a very limited set of capabilities to visualize (time range), filtering (try to fetch only relevant info for Istio context), searching (try to correlate some happening with metrics and tracing tab).

This issue is an EPIC to track several efforts around the logging Kiali logging feature.

Some of the initial identified issues could be (not ordered):

Client-Side:
- [x] Enhance UI Logging tab https://github.com/kiali/kiali/issues/2203
- [x] Tail option https://github.com/kiali/kiali/issues/2667
- [x] Horizontal/vertical Layout for app/proxy logs https://github.com/kiali/kiali/issues/2700
- [x] Add Hide log entries: 
- [x] Add Show log entries for logs https://github.com/kiali/kiali/issues/2831
- [x] Add Regex Filtering to show/hide logging: https://github.com/kiali/kiali/issues/2892
- [x] Properly handle/format invalid regex for show/hide (**WIP**) https://github.com/kiali/kiali/issues/2973
- [x] Logging Full screen option: https://github.com/kiali/kiali/issues/2691 (**WIP**)
- [x] Add Start/End Date/Time controls: https://github.com/kiali/kiali/issues/3067(**WIP**) // jshaughn: this may be something bigger than logs, see issue discussion.
- [x] Ability to turn on/off specific log windows https://github.com/kiali/kiali/issues/2765
~~ Provide some control from Kiali around logging https://github.com/kiali/kiali/issues/1525 // jshaughn: removing from epic, keeping as separate backlog item.
- [x] Refactor Refresh controls in Log tab: https://github.com/kiali/kiali/issues/3011

Server-Side
- [x] Convert log text into log entries https://github.com/kiali/kiali/issues/3264
- [x] Support endTime filtering https://github.com/kiali/kiali/issues/3303
~~ Filtering by Debug/Info/Warn/Error~~ // jshaughn: I think existing UI Show/Hide is good enough for now
~~ Investigate passive crawling for health // jshaughn: still under discussion
~~ Enhance processing of raw logging https://github.com/kiali/kiali/issues/1559 // jshaughn: removing from epic, keeping as separate backlog item.

**Comment by mtho11** [comment]
Probably best in class solution is:

- https://grafana.com/oss/loki/

- https://www.datadoghq.com/log-management/ (especially their contextual support with everything else)

**Comment by lucasponce** [comment]
@mtho11 I don't understand your comment

**Comment by jotak** [comment]
There's something I'd love to see,, I'm not sure if this is something already covered by one of the subtasks, it would be to somehow scan logs and report failures (ie. high occurrence of "Error", "Fatal", "Panic" ... words) within service health.

The tricky thing is that it wouldn't be done from the Logs screen itself, that's something to run either in the background or while processing health, so it can raise some performance challenges.

But that's definitely something that would be great, because it's quite common to have a false impression of things being "fine" whereas logs are full of errors.

**Comment by jshaughn** [comment]
@mtho11 @lucasponce I'm closing this Epic as I think we've reached a nice point in our log tab view.  We still have some open log-related issues but I think we can now proceed feature-by-feature, with each feature being an issue or itself an epic.  Mike started a good thread on dev-list, let's keep that rolling and decide on what will give us the best value re: logging.
