### ISSUE TITLE
Improve filtering capabilities of Overview and List pages

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#2233]
Overview and List pages provide filtering feature on several criterias.
Additional criteria can be added like filtering by labels or validation status.

These are some of the tasks identified for this effort:
- [x] Filtering by validation status in Istio Config List https://github.com/kiali/kiali/issues/1557
- [x] Filtering by label in Overview page https://github.com/kiali/kiali/issues/1522
- [x] Filtering by label List pages https://github.com/kiali/kiali/issues/1511
- [x] Show labels in Kiali Lists and Overview  https://github.com/kiali/kiali/issues/2547
- [x] Labels filtering: "all of" / "any of" switch  https://github.com/kiali/kiali/issues/2734
- [x] Labels filtering: click on labels to filter https://github.com/kiali/kiali/issues/2735

**Comment by jotak** [comment]
I'd have a couple of suggestions of improvements, not sure if they could be part of this epic or should be standalone tasks (let me know what you prefer).

Currently here's how it looks like:
![Capture d’écran de 2020-05-05 11-05-47](https://user-images.githubusercontent.com/2153442/81051743-93a3b300-8ec2-11ea-9426-c9d30fa627d7.png)

1. It's not obvious what is the boolean operation performed with multiple labels: OR or AND ? So, the screenshot above shows it's a OR. Which is good to widen the search space but not to narrow it. Perhaps we could show a small switch in the UI, showing "all of" / "any of", to leave this choice to the user?

2. It would be really nice if one could just click on a label from the list to automatically add it to the filters. If you ever used Kibana for instance, it's a simple yet powerful way to navigate in data & refine searches.

**Comment by jotak** [comment]
I've created two feature requests, perhaps it can go under this epic, as you prefer:

- https://github.com/kiali/kiali/issues/2734
- https://github.com/kiali/kiali/issues/2735

**Comment by aljesusg** [comment]
The research should be removed from this epic. I'll close this one

**Comment by aljesusg** [comment]
> I've created two feature requests, perhaps it can go under this epic, as you prefer:
> 
> * #2734
> * #2735

Oh I didn't see this. Agree

**Comment by lucasponce** [comment]
I think this EPIC is almost done and merged in master.
Any followup issue can be handled like a regular bug.
