### ISSUE TITLE
Improve health check of Istio subcomponents

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#2235]
Kiali assumes by default that Istio control plane is up and running.
If some of the subcomponents of Istio are not healthy (i.e. a pod is down), probably Istio won't work correctly.
It would be very useful if Kiali could add some support to those situations.

This epic is to research and track effort in detect health check of Istio subcomponents.

Some related tasks:

- [x] Check if Istio is deployed correctly https://github.com/kiali/kiali/issues/1377
- [x] Istio subcomponents health: allow components to be installed in different namespaces https://github.com/kiali/kiali/issues/2916
- [x] Research and bring info about proxy status https://github.com/kiali/kiali/issues/1615, https://github.com/kiali/kiali/issues/400, maybe https://github.com/kiali/kiali/issues/1399
- [x] Add indication if certificates are managed by Citadel or external tool https://github.com/kiali/kiali/issues/1577 (research)

**Comment by xeviknal** [comment]
The issue can be closed now. 

- Istio Subcomponents health has been put in place (#1377)
- Proxy-status has been introduced too (https://github.com/kiali/kiali/issues/1615)
- Managed certificate research has been documented (#1577)
