### ISSUE TITLE
Improve Kiali Authentication

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#2239]
Kiali offers multiple authentication strategies but still one of the most numerous community issue categories is authentication.   We need to again review what we offer and perhaps look to offer something more comprehensive.

SubTasks:

- [X] Review existing strategies for usefuleness
- [x] Decide which existing strategies to keep, discard, enhance
- [x] Decide whether to add a new, comprehensive strategy and if so, develop

Related Issues:
https://github.com/kiali/kiali/issues/2222
https://github.com/kiali/kiali/issues/2216
https://github.com/kiali/kiali/issues/2180
https://github.com/kiali/kiali/issues/2056
https://github.com/kiali/kiali/issues/1848
https://github.com/kiali/kiali/issues/1655

---

Implementation subtasks:

- [x] #2728 Remove RBAC limitation in plain Kubernetes for token auth strategy
- [x] #2056 Implement generic OAuth/OpenID authentication strategy
- Remove LDAP authentication strategy
  - [x] #2863 Communicate deprecation to users
  - [ ] Remove LDAP authentication strategy from Kiali
- Remove Login authentication strategy
  - [x] #2862 Communicate deprecation to users
  - [ ] Remove Login authentication strategy from Kiali

**Comment by thesuperzapper** [comment]
My vote is we use DEX, which has been adopted by a few major K8S projects including Kubeflow and Argo-CD.

https://github.com/dexidp/dex

**Comment by jmazzitelli** [comment]
We are probably going to first invest in a [KeyCloak](https://www.keycloak.org/about) implementation. Then again, first community member to submit a complete implementation PR wins :)

**Comment by israel-hdez** [comment]
Please, read this document and share your feedback: https://docs.google.com/document/d/1Zc4QXEUm4wfa5u8NQv_8RdzQokwsfrOR7F8os_uGch4/edit?usp=sharing

There is a proposal about how to improve auth mechanism. Check if it's OK for you and/or propose something else if you disagree.

**Comment by israel-hdez** [comment]
OpenID authentication is in place.
Both KeyCloak and Dex should work, and any other OpenID provider should work. To be released on Kiali v1.19.

**Comment by andye2004** [comment]
Really good to see this coming in. My attention has been elsewhere for the last few months and I've missed the whole conversation around the refactoring of the auth mechanism but I think the adopted approach is the right way to go. Thanks for all the effort guys, I'll look to pull the new release in and get the Dex integration in play as soon as I can find some time away from current commitments.

**Comment by israel-hdez** [comment]
This needs to discuss when `login` and `ldap` are going to be fully removed.

**Comment by jshaughn** [comment]
@israel-hdez We deprecated in Kiali 1.19.0 and Istio 1.6 is the current upstream supported version.  I think we can remove the deprecated strategies when Istio 1.6 goes out of support (likely when 1.8 is released).  If you agree we can update the Kiali 1.19.0 release notes with this information.

**Comment by israel-hdez** [comment]
@jshaughn Agreed. It's a few months from now, but quite fine. This will ensure that quite a lot of people will see the deprecation message on next Istio version (because the "bundled" Kiali of istio 1.6 does not have the message). So, sounds like the right approach.

**Comment by israel-hdez** [comment]
No more actions in this issue for the moment. I'll pull this out of the sprint.
Let's wait until Istio 1.8 release is scheduled to know when we can continue on the remaining tasks.

**Comment by jshaughn** [comment]
@israel-hdez I think we can close this epic, and open new issues as needed!
