### ISSUE TITLE
Visualize requested service routing

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#2240]
This is a long-standing visualization enhancement for see in the graph the requested service, in addition to resulting destination service.  In Istio a request for service A can be re-routed and/or mirrored via virtual service.  Today we only see telemetry for the resulting destination service, and nothing for mirrored requests.  This is due to standard Istio telemetry not reporting the requested service information.

In fact the information exists if configured to be reported.  And it is likely that by istio 1.6 it will become standard.  We could begin work on this feature as long as it was backward-compatible  (a no-op if the fields are not present, otherwise the feature is present).

Relevant Istio proposal:
https://docs.google.com/document/d/1--R1QNACYeWgPMqg5wNdKVY2vmh5FeG_CX4_yByOsMI/edit

Related Istio proposals:
https://docs.google.com/document/d/1TzXjvbEqeRKHQ7FonAY_yS1zHa8rVH2DIq4EM5BuDQ4/edit#heading=h.xw1gqgyqs5b

Related Istio Enhancement Issue: https://github.com/istio/istio/issues/21820

SubTasks:

- [x] Design the visualization #1602
- [ ] POC for UX/Dev feedback #2524 
- [ ] PR Coding tasks TBD

Related Issues:
https://github.com/kiali/kiali/issues/2015
https://github.com/kiali/kiali/issues/1649
https://github.com/kiali/kiali/issues/1459

**Comment by jshaughn** [comment]
Setting to "waiting external" as I figure out what we actually have to work with in 1.6.  In the end it was not technically feasible to get the fields we originally were looking for; they request_host field has been added in 1.6, but not as a default field.   We'll need to decide whether we want to continue with this effort based on whether request_host gives us enough benefit, and whether we want to push for it as a default field, or whether any feature we add would require configuring request_host as an additional field.

**Comment by jshaughn** [comment]
Removing from sprint backlog until there is enough time/priority to revisit this.  Saving some initial POC work in
https://github.com/jshaughn/kiali/tree/kiali%231602
https://github.com/jshaughn/kiali-ui/tree/kiali%231602

**Comment by jshaughn** [comment]
Closing this Epic, I don't think it's going to get done and users have not been aggressively asking for this capability.  The issue still exists but because the telemetry is not there by default, and the amount of work to provide a visualization is high, effort is probably better spent elsewhere.
