### ISSUE TITLE
Graph Toolbar UX Design

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2314]
The new Graph Filter Toolbar has collapsed two rows into a single row. On smaller screens this causes issues. How should things render on various sized screens if there is not enough room?

Issue:

![new-toolbar](https://user-images.githubusercontent.com/1312165/65475866-ee0d6900-de35-11e9-8277-35382412c15d.png)

Sub-Tasks Identified for This Epic:

- [x] Migrate Edge Label Selection to Display dropdown https://github.com/kiali/kiali/issues/2573
- [x] Use info icon for graph find/hide help https://github.com/kiali/kiali/issues/2620
- [x] Move graph type selection and graph tour icon to secondary masthead https://github.com/kiali/kiali/issues/2620

NOTE: [Secondary Masthead UX Design Doc.](https://docs.google.com/document/d/1cdi6Gya1Cv0wLojtTnb4v31xJ1RPDFKOOh9V0hhJzO0/edit?disco=AAAAGbIwUio&ts=5e9f2fc2&usp=comment_email_document&usp_dm=false)

**Comment by lucasponce** [comment]
To me this issue is still valid.
cc @kiali/ux-reviewers

**Comment by lwrigh** [comment]
We might consider moving the find to a more global level. That would probably require more changes on the back end but it's one idea for reducing the amount of items currently in the toolbar. We could potentially move it to the upper right hand corner of the content area. 

Some of the actions could also potentially be added to a kebab menu if the action is more of a single click sort of action.

**Comment by serenamarie125** [comment]
@lwrigh doing some exploration would be great, but we should also consider what conventions are in PF and OpenShift today.  Kiali is hitting something first because they have an extensive filtering capability!  Coming up with some options and reviewing with the DevTools UX team as a whole would be great as well!

**Comment by lwrigh** [comment]
Awesome that sounds like a good plan to me. We can do an audit of what Openshift is doing first and if there's overlap with Kiali we can make sure the conventions are consistent with one another. I can add a Jira issue to the DevTools UX backlog about it.

**Comment by jshaughn** [comment]
I assigned @lwrigh to this given her recent work mocking changes to the graph toolbar.  Laura, this may make a good  (we would label it "Epic".  And we could track sub-tasks in the main description while continuing the discussion in the comments.  For example, we could create a new issue for the Edge label options moving to Display, as an "Epic sub-task" and tie it to this issue.

**Comment by jshaughn** [comment]
@lwrigh Can you link to your graph toolbar mocks, ar add them here?

**Comment by mtho11** [comment]
@lwrigh BTW, what software do you use to create your mocks?

**Comment by lwrigh** [comment]
@mtho11 I use Sketch for creating wireframes.

**Comment by lucasponce** [comment]
Remember that namespace selector is a shared component in other pages.
If this is going to trigger a redesign in Graph page, I'd like to see also a proposal for other pages and trying to plan them also there.

Otherwise we enter in the risk to differentiate the experience of the user on common components.

Note, that I like the proposal in the Graph page, but I wonder the implications in Applications/Workloads/Services/Istio Config and Extensions that use the namespace selector as well.

**Comment by aljesusg** [comment]
Maybe ....move the namespace seelctor to the menu (component common to all views) and keep where the namespace selector was others filters, these for graph, labels filters like app or version for others

**Comment by jshaughn** [comment]
@lucasponce @aljesusg , I don't think this affects the shared namespace component in any way.  What I see in the code is that we have the idea of a SecondaryManifest and currently pages either use or don't use a SecondaryManifest based on the route.  Today, all users of the SecondaryManifest use DefaultSecondaryManifest, which includes only the namespace dropdown.  But I don't see a problem using a non-default SecondaryManifest that allows for us to better utilize space, as recommended by UX.  I certainly agree that it is important for the experience to be consistent across pages, so for example, the NamespaceSelector, when present, should be in te same place.  I think @lwrigh is aware of this but also sees an opportunity to better utilize the space.  As for the pending PR, I'll be showing it in the UX meeting and I'll add you guys as reviewers.

**Comment by lwrigh** [comment]
Just to reiterate, I think consistency in the placement of the namespace selector is one of the most important aspects of it. So whichever solution we end of going with, the placement of it should be consistent across the board.

**Comment by lucasponce** [comment]
> Just to reiterate, I think consistency in the placement of the namespace selector is one of the most important aspects of it. So whichever solution we end of going with, the placement of it should be consistent across the board.

This is what my comment is about.

Please, before to modify the secondary master head only in the Graph, as it's a different application, I'd like to see an approach how it may affect in the rest of the pages.

**Comment by lwrigh** [comment]
We could start off by keeping the location of the namespace dropdown consistent across the other pages.

**Comment by jshaughn** [comment]
@lucasponce @lwrigh , Just to be clear, the namespace dropdown location remains exactly the same in this design and in the PR.  In fact, [see the PR](https://github.com/kiali/kiali-ui/pull/1725) for the vertical separator used to visually separate the global and local information.

**Comment by lucasponce** [comment]
@jshaughn @lwrigh the secondary masthead was a common element in Kiali pages.
Now, with this design, we are adding/placing elements from the page into that shared element.

That's not bad, but I see this effort without considering the impact on the other pages, or in other way, I would like to see how this change "use the secondary masthead for specific elements of the pages" can impact in other pages for consistency.

I have impression that this re-design was done inside the graph page only but without considering this shared/design criteria.

I'm in favor to use the secondary masthead for specific elements, but I'd like to see the impact of that change in other pages, too. (i.e. worth to place the title of the page there ? other elements to save space ? if so, how that would remain constant with the overall design of shared elements?).

**Comment by jshaughn** [comment]
The SecondaryMasthead is a generic component.  DefaultSecondaryMasthead was the impl used across several pages.  In an effort to relieve the graph page toolbar width, and improve usability (like the ability to find the Graph Tour), UX proposed a two-step path.  This is step 2.   It carries over the exact widget (namespace dropdown) and location previously set for DefaultSecondaryMasthead, so I don't think it hurts consistency.   It certainly doesn't preclude a review of the other pages' needs for a custom SecondaryMasthead.   It also doesn't preclude a further change in the Graph secondary masthead, if necessary, to maintain consistency given any further design changes.  To me this is a simple iteration but I'll re-add the Waiting UX label, and wait for @lwrigh to give this PR the green light.

**Comment by lucasponce** [comment]
To put in context to @lwrigh.
The main work of this issue is related to a shared component placed in Graph page:

![image](https://user-images.githubusercontent.com/1662329/79228046-21125b00-7e61-11ea-8fea-60b2d476396e.png)

To be clear, this design looks good, no objection here. But as requested and per previous design decisions, that component was shared and the rest of the pages were designed with that restriction (to not place anything at such level):

![image](https://user-images.githubusercontent.com/1662329/79228166-4b641880-7e61-11ea-91ac-9137c7464dba.png)

![image](https://user-images.githubusercontent.com/1662329/79228236-6767ba00-7e61-11ea-83fe-1ae64d9a6d91.png)

![image](https://user-images.githubusercontent.com/1662329/79228261-72bae580-7e61-11ea-8ddf-06b8d2413356.png)

![image](https://user-images.githubusercontent.com/1662329/79228321-85cdb580-7e61-11ea-9d6f-069fb44e95d3.png)

So, if now the secondary masthead is used for components that belongs to the page, is this design valid, do we want to use that space (i.e. to place the title, etc).

**Comment by lwrigh** [comment]
For the graph toolbar it looks good to me. 

I think we should open a separate issue to look at the placement of the namespace dropdown across the board. We should aim to have it placed consistently across the board when it is appropriate.

**Comment by lucasponce** [comment]
> I think we should open a separate issue to look at the placement of the namespace dropdown across the board. We should aim to have it placed consistently across the board when it is appropriate.

Well, that's the point. Yes and no.

I'm ok to progress with the graph, but if we link with this problem, because it's related.

As the namespace dropdown was a common/shared component, I'd like to have a guideline about how to act in the other pages.

Otherwise we are taking different design of shared/common components in different pages.

**Comment by lwrigh** [comment]
I put together a design doc that outlines guideline suggestions for how we could handle the secondary masthead in table view pages and more visually dynamic pages like card or topology views. Feel free to take a look at it and leave any feedback or questions you might have: https://docs.google.com/document/d/1cdi6Gya1Cv0wLojtTnb4v31xJ1RPDFKOOh9V0hhJzO0/edit?usp=sharing 

I'm going to add it to the UX weekly agenda so we can discuss it in the next meeting.

**Comment by lucasponce** [comment]
@jshaughn @lwrigh I think we have addressed graph and refined the other pages.
I'd close this one, it seems everything is ok.

Please, if you think there is anything missing, don't hesiate to re-open and comment.

Thanks.
