### ISSUE TITLE
Support to PeerAuthentication resource

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#2520]
Istio 1.5 has introduced the PeerAuthentication[0] resource for managing mTLS between workloads in the mesh.

The task regarding mTLS [1] has replaced the Policy[2] by the PeerAuthentication. I expect users to increasingly use this new resource instead of the old Policies. The old Authentication task [3] is still working. Thus, the Policy object is still working.

I propose this to be an small epic with the following sub-tasks:
- [x] Add the resource to Istio Object list and details pages [ kiali/kiali#2739 ]
- [x] Masthead lock icon should support this new resource [ kiali/kiali#2747 ]
- [x] Overview cards should consider this new resource [ kiali/kiali#2747 ]

[0] https://istio.io/docs/reference/config/security/peer_authentication/
[1] https://istio.io/docs/tasks/security/authentication/authn-policy/
[2] https://istio.io/docs/reference/config/security/istio.authentication.v1alpha1/
[3] https://archive.istio.io/v1.4/docs/tasks/security/authentication/authn-policy/

**Comment by xeviknal** [comment]
This is the working document were the PeerAuthentication CRD was discussed: https://docs.google.com/document/d/1RAsCl4n_F75ANAXrbI9tllA8QmE4etQ3HBHXNjxLPTo/edit#

I've been told that Authentication Policies are going to be erased in Istio 1.6. Right now, for Istio 1.5, they are not officially deprecated but sent to lower priority.

In the Istio upgrade notes to 1.5, there is a section talking about that:
https://istio.io/news/releases/1.5.x/announcing-1.5/upgrade-notes/#authentication-policy

Note: AuthenticationPolicies and PeerAuthentications can coexist. However, PeerAuthentications have higher priority. Meaning that in case of override the newer object will be applied.

Note2: RequestAuthentication objects are also introduced in Istio 1.5.

My consideration would be not to wait before 1.6 to introduce those new objects. Official documentation points to these new objects instead of the old ones.

**Comment by xeviknal** [comment]
Reference to deprecation of Authentication policies: https://github.com/istio/istio/pull/22275

**Comment by xeviknal** [comment]
Closing this. Approached in https://github.com/kiali/kiali/pull/2747
There is an upcoming effort for adding extra validations into this resource: #2086 from the epic #2227
