### ISSUE TITLE
Library Updates for snyk or other reasons

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2600]
This is just a running epic to track library updates we may need to perform based on Snyk recommendations or other sources of security issues.  We can use it to track updates, add most recent to the top:

Snyk Report: https://app.snyk.io/org/kiali

**kiali-ui:**
- [ ] update tippy (v3 no longer supported)
- [x] update lodash https://github.com/kiali/kiali-ui/pull/1847 [Jul 10, 20]
- [x] update react libs https://github.com/kiali/kiali-ui/pull/1764 [May 1, 20]
- [x] remove unnecessary react deps https://github.com/kiali/kiali-ui/pull/1762 [Apr 30, 20]
- [x] update PF4 libs https://github.com/kiali/kiali-ui/pull/1726 [Apr 21, 20]
- [x] update axios https://github.com/kiali/kiali-ui/pull/1703 [Apr 8, 20]
- [x] update cytoscape popper https://github.com/kiali/kiali-ui/pull/1702 [Apr 6, 20]

**kiali:**

**Comment by aljesusg** [comment]
Maybe I would add tippy, the version 3.X is not supported only >=5

What do you think @mtho11 ?

Docs: https://atomiks.github.io/tippyjs/

**Comment by jshaughn** [comment]
@aljesusg I will add it to the list.  If I recall, we may have some work to do for that update, right?

**Comment by mtho11** [comment]
If I remember correctly there were issues so we should probably do it as a separate PR. Do you agree @jshaughn?

**Comment by jshaughn** [comment]
@lucasponce It would be great if we had a more predictable process around library updates.  I firmly believe we need to perform updates on a regular basis to help avoid downstream (and possible upstream) CVE issues.  But I am also against blanket updates of all deps to the most recent versions, that is a stability nightmare and a time waster.

So as an initial proposal what do you think about this idea which is both reactive and proactive:

- In the first week of each sprint we address Snyk's High Priority vulnerabilities.
- We start to establish a list of "important" libraries and update those that have not been updated in at least 4 months.  This would not include major version jumps, just minor or patch.  This would be stuff like react, redux, pf, etc...

**Comment by jshaughn** [comment]
@lucasponce @mtho11 @israel-hdez Note, I am disabling the automatic PR generation from snyk as we try and establish a process around dep updates.  Personally,  I think the PR generation is annoying and I don't like the branches it creates.

**Comment by mtho11** [comment]
@jshaughn yes that makes sense to disable the automatic PR generation. Most of the time we upgrade several libs at a time that are related.

**Comment by lucasponce** [comment]
This Epic seems mostly addressed.
I'm going to close it, probably tippy changes woudl require a different/new issue as it may have other implications.
