### ISSUE TITLE
introduce kiali-operator git repo

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#2618]
We need Kiali Operator source code separate from the Kiali Server source code. The Kiali Operator should not be in lock step with versions/branches of the Kiali Server. It is best to do this with a separate repo, analogous to what [Maistra does with its operator](https://github.com/Maistra/istio-operator). But we also want to be able to easily develop and run/test operator with Kiali like we do today.

- [x] create new kiali/kiali-operator github repo: https://github.com/kiali/kiali/issues/2653
- [x] jenkins needs to build the operator releases from the new git repo: https://github.com/kiali/kiali/issues/2652
- [x] create a new kiali.io link so it can replace git.io/getLatestKialiOperator: https://github.com/kiali/kiali/issues/2654
- [x] update kiali.io getting-started documentation so it refers to the new kiali.io/getLatestKialiOperator link: https://github.com/kiali/kiali/issues/2655
- [x] implement a new default detection mechanism - when not told what kiali image version to install, what kiali image tag should the operator use?: https://github.com/kiali/kiali/issues/2666

**Comment by jmazzitelli** [comment]
kiali.io/getLatestKialiOperator link is ready and so is the change to the getting-started documentation. This is done in this PR: https://github.com/kiali/kiali.io/pull/225

We do not want to merge that until the kiali-operator github repo is created and ready for us.

**Comment by jmazzitelli** [comment]
The new kiali-operator repo will be available and ready when these two PRs are merged:

* kiali PR: https://github.com/kiali/kiali/pull/2659
* operator PR: https://github.com/kiali/kiali-operator/pull/1

**Comment by jmazzitelli** [comment]
The Jenkins build has been updated to be able to build the operator separately or together with kiali (it is just added functionality to the jenkins job we already have). This is in: https://github.com/kiali/kiali/pull/2659

**Comment by jmazzitelli** [comment]
The default kiali image pulled in by the default playbook will now be "lastrelease". This is: https://github.com/kiali/kiali-operator/pull/2.

**Comment by jmazzitelli** [comment]
The order of PRs to be merged should be:

1. https://github.com/kiali/kiali-operator/pull/1
2. https://github.com/kiali/kiali-operator/pull/2
3. https://github.com/kiali/kiali/pull/2659
4. https://github.com/kiali/kiali.io/pull/225

**Comment by jmazzitelli** [comment]
This is done.

The new Kiali Operator repo is live. The old operator code has been removed from the Kiali git repo.

ACTIONS TO DO:

1. Fork the new github repo: https://github.com/kiali/kiali-operator
2. Clone it in a separate local directory wherever you want (e.g. $HOME/source): git clone git@github.com:kiali/kiali-operator.git
3. Go to your existing local kiali/kiali repo (not the operator repo you just cloned) and pull the master branch: git checkout master && git pull
4. At this point, the operator/ directory is gone, create a softlink to your new clone: ln -s <where kiali-operator is cloned> operator

At this point, you are done. "make" works the same as before. Also, unless you are changing operator code, git workflows are the same as well.

SOME SIDE EFFECTS YOU HAVE TO BE AWARE OF:

1. If you are changing operator code, you will need to do so in its separate git repo (create separate branches/PRs from there). But this is no different when working in, say, kiali-ui and kiali.io. It's just the softlink let's you do this from within the operator/ directory inside the local kiali repo. You are free to work with git directly in your separate kiali-operator clone directory if you feel more comfortable doing that. You only need the softlink if you want to continue to execute some of the make targets as before (like "make operator-create", "make kiali-create", "make cluster-push-operator", et. al.)

2. Our git.io/getLatestKialiOperator link has been decommissioned. Our getting-started guide now tells people to use kiali.io/getLatestKialiOperator. This was required when we decided to remove the operator/ directory, but it is a good thing nonetheless because it means we no longer ask customers to run a script from a domain (git.io) we have no control over. We now have full control over the kiali.io link.

3. Because our older branches (like v1.12) still have the operator/ directory, anytime you need to backport code and thus need to checkout those branches, your softlink will be deleted and you will get the operator code from those branches. When you git checkout master again, you will need to recreate the operator/ softlink again. If we find that this gets annoying, we can choose to delete the operator/ directory from the v1.0 and v1.12 branches (since the operator code for those branches are also located in the kiali-operator repo, we don't lose that code).
