### ISSUE TITLE
Add request classification information to graph

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#2854]
Istio 1.6 introduced a new [experimental] [feature for request classification metrics](https://istio.io/docs/tasks/observability/metrics/classify-metrics/).   Istio users have long-requested route-specific metrics but these are not technically feasible due to the cardinality explosion that results from route-specific time-series.  The solution is to group similar requests/routes into a more limited set of "operations".  Cardinality will increase but if following best practices it should be manageable.

The end-result is that metrics may now provide a "request_operation" label that contains the operationId.  Note that the label name "request_operation" is actually configurable by the user but I think it's fine for Kiali to require "request_operation".

There is also the ability to perform response code classification but that is out of scope for this RFE and I don't currently see a use for this in Kiali, but rather for user-specific dashboards or alerting.

Epic Tasks:
- [x] Graph design work https://github.com/kiali/kiali/issues/2856
- [x] Graph generation work #2908 
- [x] Graph side-panel work #2908
- [x] Documention  #2969
- [ ] Blog (optional)

Note that this Epic is specific to showing this information in the graph and side-panel.   We can decide later whether some sort of detail view makes sense.

**Comment by jotak** [comment]
>  Note that the label name "request_operation" is actually configurable by the user but I think it's fine for Kiali to require "request_operation"

IMO it's better to make that name configurable. The name "request_operation" is really taken as an example in this doc/task I think. It's not even a default value.

**Comment by jshaughn** [comment]
May still do a blog, but the main items are complete.
