### ISSUE TITLE
Divide the release pipeline

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#2895]
This task is about the release pipeline in https://github.com/kiali/kiali/tree/master/deploy/jenkins-ci.

Currently, it handles releasing the front-end to NPM, the back-end (bundled with the front-end) as a container image, the operator as a container image, the website, and kiali helm charts. It also updates the repositories in preparation for the next release.

The pipeline is becoming big and it's doing unrelated tasks. The only thing that share in common is that all tasks are ran when it's time for a new Kiali release.

In order to bring better maintenance to the pipeline, the _divide-and-conquer_ principle should be applied to it:
* [x] Extract the _release operator_ part to it's own pipeline kiali/kiali#3567, kiali/kiali-operator#233
* [x] Extract the _release website_ part to it's own pipeline kiali/kiali#3540, kiali/kiali.io#335
* [ ] Extract the _release Kiali app_ to it's own pipeline
* [x] Extract the _release helm charts_ to it's own pipeline kiali/kiali#3546, kiali/helm-charts#27
* [ ] Then, the original _kiali-release_ pipeline would become a simple pipeline that orchestrates running the other pipelines in the right order (because there is some implied order).
* [x] While doing the refactoring, it will be good if the number of parameters can be reduced, because some of these can be built from a more simple parameter. #3783
* [x] Update Jenkins's README.md. #3783
- [x] Add notifications for failed builds. #3783 (only for main pipeline)

**Comment by israel-hdez** [comment]
I've finished most of the planned tasks.
The remaining ones, I'm not doing them for now. They are, probably, not worth the time at the moment.

So, I'm closing as done.
