### ISSUE TITLE
Istio 1.7 issues

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3052]
Parent task for listing issues related to istio 1.7.

To install istio 1.7 you can follow steps described on https://preliminary.istio.io/latest/docs/setup/getting-started / download pre-releases https://github.com/istio/istio/releases

- [x] Wrong istio version in about dialog https://github.com/kiali/kiali/issues/3032
- [x] Sub-components names changed https://github.com/kiali/kiali/issues/3027
- ~[ ] Missing response time edge labels https://github.com/kiali/kiali/issues/3053~
- [x] Missing custom dashboards https://github.com/kiali/kiali/issues/3055
- [x] Update quick-start page with new addons system
- [x] Helm charts https://github.com/kiali/kiali/issues/195
