### ISSUE TITLE
Review Istio Management Use Cases

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3174]
There are some planned work around Wizards, and more in general, around Istio Management Use Cases.

Kiali has now support for actions on Namespace, Workload and Services, this opens more scenario like apply security on a entire Namespace, apply traffic security rules focused on a Workload or extend the existing scenarios (add Mirroring, Circuit Breaker, Fault Injection).

A highly number of scenarios are already supported in Kiali:
- Weighted Routing
- Matching Routing
- Suspend Traffic (Fault Injection)
- Create Ingress/Egress definitions
- Create Security Istio configuration

But those require a first review to:
- Better wording alignment, to not enter of synonyms that may confuse user (if Istio uses a term, let's re-use the same term in the same context).
- Some Wizard as Suspend Traffic may benefit of a clear terminology.
- Apply high level Security wizards, instead to manually create config.

So, we have identified some subtasks for this epic:
- [x] Align wording for [Weighted Routing, Matching Routing] -> [Traffic Shifting, Request Routing].
- [x] Workload Wizard to apply Security using existing traffic as input https://github.com/kiali/kiali/issues/2924.
- [x] Revisit "Suspend Traffic" into a better "Fault Injection" scenario. https://github.com/kiali/kiali/issues/3178
- [x] Update Kiali.io and promote better Tasks scenarios done using Kiali https://github.com/kiali/kiali/issues/3488
- [x] Add support to TCP Shifting / Routing scenarios https://github.com/kiali/kiali/issues/3327
- [x] Support "Request Timeout" scenario in Wizards https://github.com/kiali/kiali/issues/3183
- [x] Support "Circuit Breaker" scenario in Wizards https://github.com/kiali/kiali/issues/3191
- [x] Support "Mirroring" scenario in Wizards https://github.com/kiali/kiali/issues/3476
~~Enable/Disable Mutual TLS by Namespace granularity (control plane namespace can be used for global mesh scenario) https://github.com/kiali/kiali/issues/3363~~

**Comment by lucasponce** [comment]
cc @xevikna @jshaughn I think we have commented about all of these but I haven't a proper issue.
Feel free to add comments on it.
Will start to work on the minor ones.
