### ISSUE TITLE
Investigate vendor-support of Kiali architecture

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#3314]
For Kiali to support other mesh implementations it needs end-to-end support for additional vendors.  Today the implementation is Istio-specific.  If contributors were interested in adding support for other meshes/apis, what sort of work would be needed in Kiali to adapt to those vendors?  It would mean, perhaps, support throughout Kiali to "hide" unimplemented features.  Code-wise it would likely mean compartmentalizing the code under large vendor-specific umbrellas.

For example, the graph code currently has some architectural hooks in this area. Tt's never been put to the test but simply passing the &vendor= query parameter could invoke a completely separate code block for generating the trafficMap used to generate the cytoscape config.

- [ ] identify the kiali components/abilities that could be vendorized
- [ ] identify an approach for compartmentalizing the code
- [ ] identify an approach for hiding/enabling features
- [ ] POC of a feature

**Comment by abonas** [comment]
I wonder what hiding features means here - does it mean entities that don't exist, or functionality, like some action that exists in a wizard that other vendor doesn't have? or both :)

**Comment by jshaughn** [comment]
> I wonder what hiding features means here - does it mean entities that don't exist, or functionality,

It means the ability to hide/disable options that a specific vendor does not support.

**Comment by jshaughn** [comment]
Removing from backlog as this is not a near-term goal.

**Comment by lucasponce** [comment]
I'm revisiting this issue.
I think it suits better a discussion before to create the Epic.
I suggest to close it (let's reopen it when discussion have progressed).
