### ISSUE TITLE
Remove Mixer dependencies

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3328]
With Istio 1.8 Mixer depdendencies should be completely deprecated.
So, it's reasonable to remove them from Kiali for the version planned to be paired with Istio 1.8 release.

It would also affect to extension that use Mixer, so probably all 3scale code should be removed (3scale wizards would be supported only in 1.24 branch).

- [x] Remove mixer config https://github.com/kiali/kiali/issues/3341
- [x] Remove support for *_app and *_version telem attributes  (assume *_canonicalService, *_canonicalRevision) https://github.com/kiali/kiali/issues/3340
- [x] Remove use of istio_request_duration_seconds (assume istio_request_duration_milliseconds) https://github.com/kiali/kiali/issues/3338
- [x] review kiali.io for any necessary updates https://github.com/kiali/kiali.io/pull/327

**Comment by jshaughn** [comment]
Removing mixer/telem V1 support isn't really tied to upstream 1.8 but rather downstream needs.  I think we need to wait for OSSM to adopt 1.8+.

**Comment by jshaughn** [comment]
+1, I see the confirmation for downstream, let's get this stuff removed!

**Comment by jshaughn** [comment]
All subtasks completed.
