### ISSUE TITLE
Showing deep dive envoy config at workload level

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#3346]
This is an epic for adding all the envoy-related information at workload level page.
Based on [1], there are a lot of envoy-related data that could show to user in order to ease the debugging task to users experiencing problems in their mesh.

- [x] Show Envoy config dump https://github.com/kiali/kiali/issues/3203
- [ ] Show Envoy config dump diff https://github.com/kiali/kiali/pull/3551
- [x] Show Envoy Discovery Services data [2] https://github.com/kiali/kiali/issues/3203
- [x] Filter Envoy Discovery Services by port, address, name, etc. https://github.com/kiali/kiali-ui/pull/2051

This task is intended to:
- Show the information at workload details page.
- Show it in a modal page (not a new tab, not new page).
- Accessing it through the action drop-down (where kiali actions are usually placed).

[1] https://istio.io/latest/docs/ops/diagnostic-tools/proxy-cmd/#verifying-connectivity-to-istiod
[2] https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/dynamic_configuration
