### ISSUE TITLE
Enhanced logs viewing and correlation

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#3499]
The original title here was, "Correlate Traces with Logs".  After the discussion below we decided to make this into a more general Epic for enhancing what we do with logs.  I'm going to add some initial subtasks to try and capture some of the ideas, roughly ordered in a way that may make sense:

- [x] Update the currrent logs view to be more flexible and space efficient, with an eye towards composability. https://github.com/kiali/kiali-ui/pull/2104
- [x] Update the current logs view to better display access logs https://github.com/kiali/kiali-ui/pull/2104
- [ ] Provide a composable (popup/dialog) logs view with a configurable time period
- [ ] Use the composable logs view for better correlation

Original Description Below
=================
This issue starts a conversation on showing tracing information alongside the logging information to better understand what is going on with application performance and/or errors.

Logging information by itself is very useful for understanding what an application is doing performance-wise. That combined with jaeger tracing (possibly as an overlay) would allow easier identification of hot spots and their relevant logging/tracing data in an easily digestible format.

**Comment by jotak** [comment]
And that could also work the other way around, from the tracing page, have the ability to show logs from a limited time frame as contextual information of a given span...

**Comment by lucasponce** [comment]
> Logging information by itself is very useful for understanding what an application is doing performance-wise. That combined with jaeger tracing (possibly as an overlay) would allow easier identification of hot spots and their relevant logging/tracing data in an easily digestible format.

I agree, I'd suggest to build a story.

One thing that shares logging and tracing is the huge amount of information they provide and the difficulties to "stop" in the right place due lack of histogram or summarized info.

So, in that direction, the current work with tracing has been to combine with the telemetry data to basically respond to that: "from all information I get, which is the interesting one I should stop by".

Sharing the time controls is a good start, I guess now those controls are better normalized and it can be extended the sync between time selection from logs/metrics + tracing.

Also another suggestion from my side would be to transform the proxy-logs in some format better structured due we know what to expect, I see this impossible / hard to do in the application container due any application and use its own format, but proxy log format is more or less fixed.

That would help to jump to next steps which could be as @jotak thinking how to correlate this info, which from high level user I'd say:
- To use the telemetry to spot the desired interval to investigate.
- Move across tracing, metrics, logs, with the desired interval, and help to analyze what happened.
- Also, try that user use raw data in proxy-logs but structure data that may help to spot easily a problem and examine / link with the app log data (which is what it is).

**Comment by mtho11** [comment]
I do agree with @jotak on starting from the tracing page and then jumping to show logs. I'm simply saying that the tracing information should be available from the logs (once I've jumped) and that information overlayed with the logging information in some visible way so that the two are composed (and correlated).

**Comment by mtho11** [comment]
And yes, @lucasponce your last 3 key bullet points are spot on.

**Comment by jshaughn** [comment]
@jotak @lucasponce I'd like to maybe move this forward a bit.  What do you think about a log component more adaptable to being available to other views, and not just its own dedicated tab?  So that users could more easily see logs for a time of interest, determined by the controlling page, and on screen with the other view.  Possibly expanded in an embedded way, or maybe as a launched dialog.    When a user is looking at an interesting trace, or perhaps has used a brush to select a time period in a chart, or perhaps even from graph replay workload node, or something like that; to then be able to see relevant logs at the same time, without actually having to navigate away to the logs tab.

I'm also considering a POC to change the logs view, replacing the "splitter" view with a single pane, integrated view.  Meaning for the selected containers, intersperse logs by time, using color and a short prefix to identify the entries.

**Comment by lucasponce** [comment]
I think this issue was created after an interesting discussion in kiali-dev where several ideas were proposed.

This deseves a more deep discussion before to start any effort, as now features have more implications and integration with all pages/components, but some early comments:

- To show logs in a modal when user is studying a specific chart or trace is a good idea, but that feature should respond to a correlation scenario, I wouldn't confuse the user that now logs belongs to other entities rather than the Workload.
- Application logs can not be pre-processed and user would understand that, but Istio proxy logs and Istio control plane logs can be processed and filtered and show the interesting elements to the user, I don't think just a syntax colored is something that adds value.

> I'm also considering a POC to change the logs view, replacing the "splitter" view with a single pane, integrated view. Meaning for the selected containers, intersperse logs by time, using color and a short prefix to identify the entries.

I'm not sure what this means. I think this issue should be moved to an Epic with Subtasks, I don't feel comfortable with this issue as it's described and added to the backlog as it is.

**Comment by jotak** [comment]
In terms of feature, totally +1 to make a log view composable so that it can be shown from different places, with the inputs as Jay describes. (In terms of organization I don't have much to say, leaving it to you :-) )

I guess that making the view composable, and adding more filtering/formatting capabilities could be two different tasks.

**Comment by lucasponce** [comment]
Adding this [1] here as it can help me to explain my vision.

Showing these logs is ok, but not real added value compared with other tool (UI or CLI) or even the existing implemented feature (yes, we can see them in a better context but that will save a click, it's more an usability enhancement rather than a business value).

But, Istio proxies are base in well known log structures that are hard to interpret unless you have the knowledge (and believe me, it's not trivial), here is where Kiali can add value in the existing feature.

Leave the container app logs as it is, because it's outside the Kiali domain, but help the user to understand what all structure and flags means.


[1] https://blog.getambassador.io/understanding-envoy-proxy-and-ambassador-http-access-logs-fee7802a2ec5

**Comment by jshaughn** [comment]
I'm going to play around with this stuff a little bit, as a lower priority activity POC/experiment.

**Comment by jshaughn** [comment]
It could be an interesting integration to time-sort and include trace lines.  If enabled I guess we would query trace info for the time-period (or maybe it would be supplied if already fetched?), that also touched the pod?   Or would it make sense for a user to select a trace of interest and then build a logs view arouns that one trace?

**Comment by lucasponce** [comment]
> It could be an interesting integration to time-sort and include trace lines. If enabled I guess we would query trace info for the time-period (or maybe it would be supplied if already fetched?), that also touched the pod?

Well, more than the pod, the workload as it's the granularity tracing may give to Kiali today by default.
Just an optional checkbox to show "Spans" similar as metrics charts would be ideal, then the span info (or a summary) can be shown with other color, correlated with the proxy/sidecar + application log.

> Or would it make sense for a user to select a trace of interest and then build a logs view arouns that one trace?

Today this usecase is started from the traces tab, which is the intended place to get the details of a trace + correlated with the metrics (it's a hard problem to select which is the trace that I want to see as a user, that's the goal of this tab), then when you select a trace, you'll see the details + spans. At this level there are the links to jump to the logs, here those links can be narrowed to point to the logs tab with the span enabled.

**Comment by lucasponce** [comment]
Regarding this comment https://github.com/kiali/kiali/issues/3499#issuecomment-836395518

If in this issue:

![image](https://user-images.githubusercontent.com/1662329/123871610-2491e500-d934-11eb-82ca-f2610f382ff8.png)

We change one of the buggy "control" per a "spans" option in green, it's pretty much what it could be showed today.

It's pure work in the UI as spans are fetched already for the metrics side, so it could be used for logs tab as well.

**Comment by jshaughn** [comment]
Seems doable.  The spans would be for the workload, the logs for a single pod in the workload, but I don't think that's any sort of problem.  The user could change pods but the spans would just remain constant.  Perhaps we should dedicate a color to anything trace/span-related.  In the graph we use a light purple for overlay, we use I think blue dots in the trace detail chart,  It would be nice if we reserved a span color here that was consistent with at least one of the other uses.

**Comment by lucasponce** [comment]
I'm moving this one to Sprint 60.
Do you think you could work on it @jshaughn ? 
Or can I ask to the team if anyone would like to take a look ?

I don't think it should be complex as I think backend is ready, as the same query is used to correlation in the metrics tab.

**Comment by jshaughn** [comment]
@lucasponce I was planning on doing this in this sprint, so yes.

**Comment by jshaughn** [comment]
@lucasponce I think adding `spans` to the unified log view is enough to close this Epic.   Further work can be done using new issues as needed.  This first iteration seemed useful enough to merge.  When you return we can revisit to see if it meets your expectation or if there is follow-on work.  One thing is that for now we use span startTime for the sorting.  I'm not sure if we want to do something with endTime (startTime+Duration), whether to show an entry for both times or maybe something fancy like highlight any entries that fall between the start and end.
