### ISSUE TITLE
Upgrade the Patternfly framework

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4260]
Subtasks:

In Review and Can be merged if no blockers:

- [x]  https://github.com/kiali/kiali/issues/4836

Issues deferred to ongoing work:
- [x] [overview styling](https://github.com/kiali/kiali/pull/4944#issuecomment-1116084808) (won't do/deferred)
- [x] [shared styling](https://github.com/kiali/kiali/pull/4944#issuecomment-1116134501) (won't do/deferred)
- [x] [preview traffic policy](https://github.com/kiali/kiali/pull/4944#issuecomment-1116085801) (won't do/deferred)
- [x] [chart tooltips](https://github.com/kiali/kiali/pull/4944#discussion_r863887582) (won't do/future)

Issues resolved post-merge:
See https://github.com/kiali/kiali/pull/4944 for a long list of issues identified during review and their status. That PR was used to track progress of all issue resolution prior to merge.   Below is the list of issues to resolve post-merge.
UI:
- [x] [button placement](https://github.com/kiali/kiali/pull/4944#issuecomment-1116085588) https://github.com/kiali/kiali/pull/5124
- [x] [find/hide styling](https://github.com/kiali/kiali/pull/4944#issuecomment-1116104500) https://github.com/kiali/kiali/issues/5125
- [x] [traffic tab columns](https://github.com/kiali/kiali/pull/4944#discussion_r863883977) https://github.com/kiali/kiali/pull/5059
- [x] [kebab placement](https://github.com/kiali/kiali/pull/4944#discussion_r863893326) https://github.com/kiali/kiali/pull/5066
- [x] [heatmap format](https://github.com/kiali/kiali/pull/4944#issuecomment-1116237903) https://github.com/kiali/kiali/pull/5066
- [x] [column headers](https://github.com/kiali/kiali/pull/4944#issuecomment-1116275027) https://github.com/kiali/kiali/pull/5059
- [x] [login screen](https://github.com/kiali/kiali/pull/4944#issuecomment-1117002636) https://github.com/kiali/kiali/pull/5101
- [x] [yaml help icon](https://github.com/kiali/kiali/pull/4944#issuecomment-1117083847) https://github.com/kiali/kiali/issues/5097
- [x] [action menu](https://github.com/kiali/kiali/pull/4944#issuecomment-1117090433) https://github.com/kiali/kiali/pull/5074

Cypress:
- [x] validate cypress feature: graph_display #5063
- [x] validate cypress feature: istio_config
- [x] validate cypress feature: kiali_cookie
- [x] validate cypress feature: kiali_homepage
- [x] validate cypress feature: kiali_login
- [x] #5050
- [x] #5056
- [x] #5054
- [x] #5052
- [x] validate cypress feature: workload_logs

other:
- [x] dependabot security issues https://github.com/kiali/kiali/pull/5095

============================

Description:

Kiali 1.48 uses patternfly versions similar to:

```
    "@patternfly/patternfly": "2.71.6",
    "@patternfly/react-charts": "5.3.22",
    "@patternfly/react-core": "3.158.4",
    "@patternfly/react-styles": "3.7.14",
    "@patternfly/react-table": "2.28.51",
    "@patternfly/react-tokens": "2.8.15",
```

But framework is moving to major versions, as an example, other consoles (like OS console) are using similar to:

```
    "@patternfly/patternfly": "4.122.2",
    "@patternfly/quickstarts": "1.1.0",
    "@patternfly/react-catalog-view-extension": "4.12.15",
    "@patternfly/react-charts": "6.15.8",
    "@patternfly/react-core": "4.135.15",
    "@patternfly/react-table": "4.29.16",
    "@patternfly/react-tokens": "4.12.5",
    "@patternfly/react-topology": "4.9.21",
    "@patternfly/react-virtualized-extension": "4.8.53",
```

So, at some point Kiali would need to perform an upgrade.

This upgrade has a high cost and typically requires a lot of work to just keep the same features working.

I've created this issue to reference other minor issues that are related to patternfly migrations.

UPDATE Mar 23, 22:   It is desirable that Kiali be compatible with the patternfly versions used in OS console.

**Comment by nrfox** [comment]
`istio_config` cypress tests look fine. Pass in CI and locally.

**Comment by lucasponce** [comment]
Graph Display is the pending test to review:
![image](https://user-images.githubusercontent.com/1662329/167787840-67d94bac-fe3d-4b1b-96b3-8e6f14f1b113.png)

**Comment by nrfox** [comment]
`kiali_login` passes locally for me when running against CRC. There's a failure with the provider section https://github.com/kiali/kiali/blob/master/frontend/cypress/support/commands.ts#L66-L68 but that existed before and is a separate issue. Otherwise the test passes. Marking as complete.

**Comment by jshaughn** [comment]
All sub-tasks completed!
