### ISSUE TITLE
Refactor API services to consolidate Health logic into the backend

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4611]
Kiali API splits services in several endpoints that are invoked by the UI to consolidate the final view:

![image](https://user-images.githubusercontent.com/1662329/146525208-1d02d657-0a21-41f9-abae-94c08b44a251.png)

This design was initially chosen during the first steps of the project and the default action was to create a new API and let the UI integrate them.

For services like Health, this pattern presents a well-known technical debt as the logic is split and the frontend code is not only rendering the data but doing business calculations.

This design "works" but in the context of scalability scenarios, it presents some performance challenges as discussed in https://github.com/kiali/kiali/discussions/4507 that should be addressed not only for a specific area but for the whole design.

The goal of this Epic is to study and propose a plan to move the Health logic (and potentially other similar endpoints) into the backend to have a robust endpoint that simplifies the UI code.

This work should take into consideration the different efforts in work in progress to adjust the backend endpoint to improve the logic on scalability scenarios.

Suggested test plan (QE @mattmahoneyrh):
- This Epic shouldn't introduce changes in the business features, so the main QE strategy should be to check feature regressions.
- Additionally QE may validate potential performance variations compared with the previous versions.
- This Epic may involve different subtasks, QE/Dev can define if regression tests may happen at the end of the Epic or a specific PR that may require a significant review.

Dev tasks:

* [x] Reduce the number of requests to fetch health data on the graph page
  * https://github.com/kiali/kiali/pull/4772
  * https://github.com/kiali/kiali-ui/pull/2316
  * https://github.com/kiali/kiali/pull/4816
* [ ] Reduce the number of requests to fetch health data on the overview page
* [x] https://github.com/kiali/kiali/issues/4748
* [x] #4790
  * https://github.com/kiali/kiali/pull/4799
  * https://github.com/kiali/kiali-ui/pull/2329
* [ ] Health metrics from graph data (remove the "perceived" duplicated fetches from prometheus)
  * https://github.com/kiali/kiali/pull/4802
  * https://github.com/kiali/kiali-ui/pull/2330

**Comment by israel-hdez** [comment]
I've been reviewing the back-end code involved to Health calculations. I still haven't checked the UI side. I've been trying to understand what we _really_ need, given what is written in this issue and also given the backing discussion https://github.com/kiali/kiali/discussions/4507.

So far, I understand this is the background:
* My understanding is that this issue is motivated by a scalability problem. In https://github.com/kiali/kiali/discussions/4507 discussion, graph performance is what motivated this issue.
* Although it's not mentioned in this epic, because of the backing discussion, I understand the scope of this issue is limited to the graph.
* The focus seems to be on the Health calculations. There seems to be an identified "mark" when health calculations takes as much time as graph generation. This mark is apparently about 200 namespaces.
* Both graph generation and health calculations are hitting prometheus and doing similar queries, which gives the idea that we could save some queries by sharing data between graph generation and health calculation.
* Because of the two previous bullets, and because graph generation precedes health calculations, this gives the perception that health is what needs to be optimized (although graph generation may also be subject to optimizations).
* Health calculations are done in the UI, and the back-end is only providing the needed data (request rates) and threshold configurations to calculate health.

My thoughts about this epic after trying to understand the background:

All in all, I think the main goal is to make Kiali to perform better when the cluster has a large number of namespaces.

This epic seems to be proposing that the logic in the UI side is moved to the back-end. This sounds complex because it involves translating typescript code to go-lang code, which can take a lot of time. At the same time, looks like we want to reduce the number of queries that are made to prometheus, which adds complexity to the problem.

I may be wrong, but my perception is that the high number of queries to prometheus is what is currently introducing the most performance penalty, because it doubles the processing time. So, IMO, this is what should be solved to close this epic.

Moving the health calculations from the UI to the back-end is something that IMO does not guarantee any performance gains _at the moment_. This refactor can potentially provide a benefit when looking at the overall scalability problem, in which apparently we are leading towards building an in-memory model of pre-calculated data to quickly feed the UI with information to display. But there is no concrete design of this. So, I am uncertain about if this refactor will _really_ help and I think this is not worth doing at the moment. Since this refactor is not trivial, I would like to see if the team agrees to delay this work for later when there is more certainty that it's worth doing.

So, for the short-term, I think it's better to focus on the immediate problem of increasing graph performance by simply trying to reduce the number of queries to prometheus. Clearly, this will only move the "mark" when Kiali is perceived with low performance to a higher number of namespaces. But since there is no epic in the backlog to start working on the overall scalability problem, IMO this is the only work that is worth doing right now.

I would like to hear what other @kiali/maintainers think.

**Comment by nrfox** [comment]
> I may be wrong, but my perception is that the high number of queries to prometheus is what is currently introducing the most performance penalty, because it doubles the processing time.

Do we have a way of measuring that? More specifically, identifying what exactly has the greatest effect on graph load times?

**Comment by israel-hdez** [comment]
@nrfox BTW, withing the dev team we don't have the resources to see it by ourselves. It's been mainly reports from users and also from the qe team.

**Comment by nrfox** [comment]
> @nrfox I think that our main reference has been the browser console, and seeing how much time each request takes to generate a reply.

It's definitely helpful to know what requests are the slowest but it doesn't necessarily tell you what is having the greatest perf impact on the graph loading. For example, if the graph is waiting for all the health information to load, it might be that the aggregated health requests are taking longer than a single slow request that requires hitting prom even though each of the health requests returns quickly. I think it'd be more helpful to measure from the front end, graph load beginning to end, rather than the server side.

**Comment by leandroberetta** [comment]
> People have already raised this issue, like here: [#3354 (comment)](https://github.com/kiali/kiali/issues/3354#issuecomment-716992548). So, storing more data in a cache IMO is a step forward in performance, but a step back in scalability. I see this my main reason for delaying this work. Until we have something that improves both scalability and performance, I don't think it's a good idea to add more pressure to memory. If you have a clear vision about how to solve this... I'm all ears :-)

Well, I guess we are talking about graph scalability, meaning, a more performant graph, that can scale up to more namespaces/workloads, like you said, expanding the current limits.

After these limits, our graph is less performant (leaving aside the fact that is difficult to navigate also, but that is another epic). I believed that we can increase performance by caching more data, in this case, health data, and that would improve the graph scalability limits.

We are not scaling Kiali, we aren't duplicating data for contingency, we are saving more data in the cache. 

As everything in engineering, there are trade offs, for sure some users would like that Kiali has the minimum footprint possible but I heard others that want to get better response times from their graphs.

Maybe an option is to have this configurable, or even a better cache that allow us to configure eviction times and data passivation.

What I believed is that Kiali needs to be performant enough to support our users scale (getting bigger architectures), and I believed both performance/graph scalability are doable.

**Comment by israel-hdez** [comment]
@leandroberetta 

> After these limits, our graph is less performant (leaving aside the fact that is difficult to navigate also, but that is another epic). I believed that we can increase performance by caching more data, in this case, health data, and that would improve the graph scalability limits.

What you are commenting makes me realize that "scalability" can have multiple dimensions.

If the graph loads quickly on big clusters, I don't think that's equivalent of good scalability if it needs a lot of resources to work.

IMHO both are needed: the graph needs to load quickly enough to provide a good user experience, while consuming a manageable amount of resources.

**Comment by lucasponce** [comment]
> My understanding is that this issue is motivated by a scalability problem. In https://github.com/kiali/kiali/discussions/4507 discussion, graph performance is what motivated this issue.
Although it's not mentioned in this Epic, because of the backing discussion, I understand the scope of this issue is limited to the graph.
The focus seems to be on the Health calculations. There seems to be an identified "mark" when health calculations takes as much time as graph generation. This mark is apparently about 200 namespaces.

I don't think those assumptions are accurate, and then the rest of the discussion may move to very different ways.

This EPIC is to move the Health and logic to an internal service that other business services can use: Overview, Graph, List, and Details.

There are multiple motivations to plan this movement:
- Today, there is a technical debt where the Health logic is not calculated in the backend; the frontend takes the configuration and the raw data and calculates what elements are healthy. That is something that presents some limitations (not only in terms of performance/scalability) but in terms of feature-wise (better filtering in the backend).
- Yes, there is an opportunity to improve performance scenarios if every business endpoint aggregates the health information (overview, graph, list, details). Health queries are already cached, but moving this service as aggregation in the backend will identify areas to improve.
- Health is a critical service, and what is health changes and can be configurable; indeed, Kiali has a service to configure that and let the users modify what is shown as healthy (Health configuration is still a supported feature in Kiali).
- Furthermore, when we see the context of production environments and other integrations, Health may have a different source (pretty soon), so having an internal service that can answer "what is the health of this element (namespace, app, workload, service)" will help to get the flexibility for future integrations.

So, with that context, my proposal for this Epic would be:
- Start adding "health" logic in the current endpoints (namespaces, graph, list, details); when the user fetches an overview, or graph, or a list, they could avoid the N queries that are required to collect the Health. This information can be done internally as a first step.
- With this movement, the "final health" can be calculated from the backend instead of from the frontend; the frontend will have the responsibility to "render" this data but not calculate it.
- In specific contexts like Overview and Graph, there will be opportunities to improve, as mentioned, and revisit what is already cached and how it can be improved and refined. Scenarios with a high level of namespaces or single namespaces with many workloads are part of the scope.
- This Epic should also consider that the sources of the Health may change, considering a graph generation comes from one source and the Health service is computed from a different one. Today is a composition of pod status plus traffic information collected by sidecars, but this information may not be available and we need a flexible design here.

This Epic is not focused on the graph scalability, which may be a side effect of part of the work, but thinking about how to improve the health service from a top-down perspective.

**Comment by israel-hdez** [comment]
> This Epic is not focused on the graph scalability, which may be a side effect of part of the work, but thinking about how to improve the health service from a top-down perspective.

I think I simply got confused since this ticket came from the scalability discussion.

> This EPIC is to move the Health and logic to an internal service that other business services can use: Overview, Graph, List, and Details.

So, I think this Epic is well defined and I don't see anything to discuss. Apparently, it's purely mechanical work.

It's very unclear to me where we want to go. Anyway, I think I'll let it be.

**Comment by jshaughn** [comment]
I agree that it is an incorrect assumption that this epic be scoped to the graph, and is motivated purely by perf/scale.  Although, I do think that the work here could result in immediate benefit to graph performance, and possibly to other areas of the UI, as the callbacks for health happen in multiple places.   

I don't think it's purely mechanical work, nor a refactor for refactor sake, but I do agree that it is maybe more infrastructural, or forward-looking in nature, than some of the other epics.   Looking at how our current API is consumed, it's clear that whenever we are displaying information, whether it be in an overview, a graph, a list, or a detail view, it always includes health information for the relevant components.   And our initial approach of pulling health information independently from component information, seems clunky and antiquated.  Instead, the notion of health as a 1st-class attribute on nearly all components, seems like a better idea.  And, as Lucas mentions, moving logic to the back-end will make our back-end API more powerful for consumption by [potentially] new clients.

So, restating some things from above, the fundamental change for this epic would be that the UI would no longer make calls to the backend for health information, instead, the returned elements would contain the information necessary for rendering health in the UI.  Some topics to consider as part of that work:

- should health be optionally returned based on caller's option
- can we cache health information:
  - types of health (traffic, pod, other...)
  - when must [each type] health data be refreshed?
- can we design our internal apis to accept health information if available from other sources
  - for example, as I mentioned in 4507, the graph could provide rate info, helping health not have to fetch it manually

As for Kiali's resource consumption, I do expect Kiali to gradually increase it's server-side footprint, but remember also that server-side resources for Kiali can extend to prometheus, jaeger, etc.  If we have a small footprint but it's because we force Prometheus to have a huge footprint, it may not be a real savings overall.

**Comment by israel-hdez** [comment]
> I don't think it's purely mechanical work, nor a refactor for refactor sake, but I do agree that it is maybe more infrastructural, or forward-looking in nature, than some of the other epics.

Yes... I think it's more clear for me what this epic is asking to do. Yet, it remains unclear for me where do we want to go :-/

**Comment by lucasponce** [comment]
> Yet, it remains unclear for me where do we want to go :-/

I think that @jshaughn and I are doing an effort to explain the motivation of this Epic and also the overall context with all the Epics defined and discussed by the team.

We would be more than happy if you can elaborate on what is unclear, as you have mentioned several times, and I'm not sure what kind of details you'd like to see in the Epic or in another format.

**Comment by israel-hdez** [comment]
@lucasponce @jshaughn 

> We would be more than happy if you can elaborate on what is unclear, as you have mentioned several times, and I'm not sure what kind of details you'd like to see in the Epic or in another format.

Perhaps we should meet to clarify more quickly. Today, I think you have a busy day. Tomorrow, I think it's similar. So, probably Wednesday is a good day to meet, unless you want to have a discussion today once you are free and you don't mind to stay a little after-hours :-)

Anyway, the motivations for the refactor (which is the main point touched in the epic) is what I see weak. All other points, like the revisit to the cache and review other sources for health are by all means worth to review, but for this I don't think a refactor is a blocker nor needed. 

Without that refactor it is still viable to aggregate health data into overview/graph/list/details endpoints to reduce the number of requests to a single one. Also, I think we still want to return the details (like request rates, pod status, etc) to show them to the user because it is valuable information. If we anyway will send the details to the UI, I don't see anything wrong with calculating health at UI side. So, IMHO, a refactor is not worth doing until we find concrete use case that forces us to move that logic to the back-end.

Adding other health sources is something that I'm +1 for opening discussions. But IMO I think this can be accomplished without this refactor.

Adding more cache to speedup health calculation is something that probably needs to be discussed per-source of health. And since we probably still want to show the details about how health was calculated (i.e. the request rates), it probably only makes sense to maintain a cache of the summarized data of each source signal and re-calculate on demand (either on back-end or front-end), rather than having a cache solely the pre-calculated health. But I see this should be discussed *first* before thinking in a refactor.

Also the point about "production environments and other integrations" is weak UNLESS we want the Kiali API to become _public_. If you today tell me that we want to make the Kiali API consumable for third parties, then I would agree that we _need_ this refactor. But that would be a change for the whole Kiali API and not only health endpoints and I would be more than happy to do not only this, but any other refactor so that the Kiali API can be consumed by any 3rd party system. However, since we have been consistently telling people that the Kiali API is private and is only meant to be consumed by our UI, and also it  has been a no-goal for the Kiali API to be consumed by 3rd parties, I don't see a case for this.

**Comment by israel-hdez** [comment]
This is moving forward by, first, reducing the number of requests that are done to fetch the needed data to calculate health. This won't move any front-end logic to the back-end. A preliminary list of tasks is the following (added to the main/first comment for tracking):

- Reduce the number of requests to fetch health data on the graph page
- Reduce the number of requests to fetch health data on the overview page
- Reduce the number of requests to fetch health data on list pages
- Reduce the number of requests to fetch health data on detail pages

After that, we will review data caching. It is possible that improving data caching requires front/back-ends refactoring, but we will review when we reach this stage.

Finally, we may start looking at what other signals can form part of health.

**Comment by nrfox** [comment]
@aljesusg @israel-hdez can the other tasks to reduce the number of requests be worked on in parallel? If so, I'm happy to pick one of those up.

**Comment by israel-hdez** [comment]
@nrfox Quite possible. I'm reviewing the graph part, but since I was out for a few days, I am still beginning with it. So, if you want to take over or pick any other one, please do.

**Comment by nrfox** [comment]
Actually I don't see multiple requests being made on the details pages except for the graph page which I think is being addressed by @israel-hdez. For example services --> detail takes you to a page that does not make any requests for health. The other workloads/apps pages are similar. Am I missing something?

**Comment by israel-hdez** [comment]
@nrfox I checked and I think you are right. Apparently we felt in the graph trap that made us think that the detail page is doing multiple requests to health endpoints, while it was the minigraph :-/

Indeed, if you deploy my PRs https://github.com/kiali/kiali/pull/4772 and https://github.com/kiali/kiali-ui/pull/2316 those request go away.

**Comment by nrfox** [comment]
I will close: https://github.com/kiali/kiali/issues/4790 then and high five myself!

**Comment by lucasponce** [comment]
Perhaps the Overview page may require a proper Epic itself.
As it's related to the big refactoring @hhovsepy is working on, it would involve not only health but different queries related to Istio configuration and validations.

**Comment by lucasponce** [comment]
I'm going to close this Epic in favor to have a specific one for the Overview page, the cross-namespace APIs, and cluster rights.
I think most of the approach of this Epic is consolidated in master.

Follow-up efforts can go in separated issues.
