### ISSUE TITLE
Create a UI suite test on cypress

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4854]
Kiali has no proper integration UI testing located in the upstream repo.

As part of the strategy to improve this, the "cypress" framework has been introduced in the "frontend" folder:

https://github.com/kiali/kiali/tree/master/frontend/cypress

But there are a couple of efforts to work on this area
- Migrate existing UI testing used by QE into "cypress" and/or redefine new UI test flows that cover all features of the project.
- Integrate the UI testing as part of the public pipelines that are being migrated into Github Actions.

@ScriptingShrimp is leading/coordinating the migration of the "legacy" UI test into cypress but the generation of UI tests would require effort from all the team.

I'm going to create this Epic as a reference for future subtasks.

Subtasks:
- [x] https://github.com/kiali/kiali/issues/4872
- [x] https://github.com/kiali/kiali/issues/4967
- [x] https://github.com/kiali/kiali/issues/4912
- [x] https://github.com/kiali/kiali/issues/4949
- [x] #5073
- [x] https://github.com/kiali/kiali/issues/5084
- [ ] UI tests around the Graph cytoscape toolbar
- [x] https://github.com/kiali/kiali/issues/4960
- [x] https://github.com/kiali/kiali/pull/4951
- [x] https://github.com/kiali/kiali/issues/4955
- [x] https://github.com/kiali/kiali/issues/4969
- [x] https://github.com/kiali/kiali/issues/5001
- [x] https://github.com/kiali/kiali/issues/5008
- [x] #5072
- [x] #5013
- [x] #5047
- [x] #5079
- [x] #5085

Subtasks specific to OpenShift testing support:
- [ ] authentication for jaeger, prometheus, other?

**Comment by nrfox** [comment]
Can we get a list of the existing UI tests and what they cover so that we can be sure to cover the same things with the cypress tests? From there we can create subtasks for the various test cases that can be worked on in parallel by anyone. IMO we need this before we can jump into writing tests if the goal is to replace the legacy UI tests with cypress. @mattmahoneyrh @ScriptingShrimp @lucasponce

**Comment by ScriptingShrimp** [comment]
@pbajjuri20 lets have a look asap.
I think we need more than day to have that list curated.

**Comment by nrfox** [comment]
@ScriptingShrimp we're going to continue forward with creating some skeleton tests for the various pages and those can be compared against the existing polarion or selenium test cases and gaps can be filled iteratively.

**Comment by ScriptingShrimp** [comment]
One PR is on a way, we can plan this properly on planning.

Important questions regarding UI regression: 
Clean Kiali instance have always istio-system namespaces present ? Also is this namespace same across all environments: crc, kind, minikube, ocp?

If so, we can do basic smokes on top of istio-system without any additional demo application. I just started questioning myself if downstream maistra have same namespace, but will check.

**Comment by jmazzitelli** [comment]
> Clean Kiali instance have always istio-system namespaces present ? Also is this namespace same across all environments: crc, kind, minikube, ocp?

Assuming all test environments are set up with Istio using the hack script `install-istio-via-istioctl.sh`, then yes, the control plane namespace will always exist and always be `istio-system` regardless of environment. The only way it won't be `istio-system` is if the person or script that installed Istio with that hack script passed in [the `--namespace` option](https://github.com/kiali/kiali/blob/v1.48.0/hack/istio/install-istio-via-istioctl.sh#L192-L194) and told it to put the control plane somewhere else. But the default is `istio-system`.

**Comment by lucasponce** [comment]
> If so, we can do basic smokes on top of istio-system without any additional demo application. I just started questioning myself if downstream maistra have same namespace, will check.

What is the purpose of these tests?

I'd prefer if we focus on features that are available to the users even for smoke tests.
The control plane namespace ("istio-system") is typically a "special case", i.e. the workloads have no sidecars.

If the smoke test is that the application opens the page and lists some basic workloads is ok, but as soon as you try to use Istio you'll see that it's better to focus on any small example based on the data plane.

**Comment by jmazzitelli** [comment]
FYI: jaeger and grafana integration tests (specifically around auth that is placed in front of jaeger and grafana) are tested (and successfully pass today on OSSM 2.2) in molecule tests [here](https://github.com/kiali/kiali-operator/tree/master/molecule/jaeger-test) and [here](https://github.com/kiali/kiali-operator/tree/master/molecule/grafana-test).
