### ISSUE TITLE
Support for Istio Gateway API

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5026]
Kiali should support the new [Gateway API](https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/) and other new networking resources such as `HTTPRoute`.

Support would entail:
- [x] https://github.com/kiali/kiali/issues/5485
- [x] https://github.com/kiali/kiali/issues/5490
- [x] https://github.com/kiali/kiali/issues/5501
- [x] https://github.com/kiali/kiali/issues/5502
- [x] Gateway API in Console Plugin

**Comment by lucasponce** [comment]
This issue is big.
It should start with supporting these new objects but it can't replace the current functionality invalidations and wizards.
Also, co-existing both implementations will have side effects as these new API is under evolution and it's not a 1-to-1 related to the Istio Gateway/VirtualService.

Another aspect is this API is optional and it requires the admin to install it separately, this would affect and it would require a "is it enabled" logic in Kiali that would add extra complexity.

So, I think we need to review this, but I don't see how Kiali can extend wizards on validations on these new objects just yet.

My recommendation is to limit the scope of this work to listing/editing these objects as a first step.

**Comment by hhovsepy** [comment]
It seems that Gateway API is not supported yet in https://github.com/kubernetes/client-go/blob/master/kubernetes/clientset.go

**Comment by jshaughn** [comment]
Taking off the sprint backlog until there is an API we can query for this kind of config.
