### ISSUE TITLE
Mesh wide settings should take the MeshConfig defaults

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#5263]
Kiali detects a mesh wide TLS setup:
![image](https://user-images.githubusercontent.com/1662329/176436949-da46ffb6-43ac-4e1e-bae2-0e129a1248c8.png)

But only when there is an explicit DestinationRule in the "istio-system" (or any other control plane namespace).

![image](https://user-images.githubusercontent.com/1662329/176437414-7ea2dc78-5f97-464b-8178-48c2d43a5d1e.png)

This logic should be revisited and considered to get the Mesh defaults and inform the user about the default mode in addition to any particular configuration that a user may perform on a specific namespace.

This issue may involve a review of some TLS validations, the current logic is valid but it should be completed with the mesh defaults.

Related to this issue, the KIA0204, KIA0205, KIA0206, KIA0401, KIA0501 validations don't seem to work well, but I'd try to address the whole TLS logic is related here:

https://kiali.io/docs/features/validations/#kia0204---mtls-settings-of-a-non-local-destination-rule-are-overridden
https://kiali.io/docs/features/validations/#kia0205---peerauthentication-enabling-mtls-at-mesh-level-is-missing
https://kiali.io/docs/features/validations/#kia0206---peerauthentication-enabling-namespace-wide-mtls-is-missing
https://kiali.io/docs/features/validations/#kia0401---mesh-wide-destination-rule-enabling-mtls-is-missing
https://kiali.io/docs/features/validations/#kia0501---destination-rule-enabling-namespace-wide-mtls-is-missing

As part of this work, the error level of these validations can be revisited (if it makes sense to keep them on "error" or just to relax the level to "warning").

Other validations are outdated, related to https://github.com/kiali/kiali/issues/5262 but it may need some review in the backend logic as well:
https://kiali.io/docs/features/validations/#kia0207---peerauthentication-with-tls-strict-mode-found-it-should-be-permissive

Subtasks:
- [x] Show info about extended mtls from mesh level in namespaces.
- [x] Show "autoMTLS true" mode info in toolbar lock icon tooltip.
- [x] Revisit existing mTLS validations while combining them with default mtls mode.

**Comment by hhovsepy** [comment]
Hi @lucasponce , can you please clarify what is wrong with the validations mentioned above? Are they not aligned with Istio?

**Comment by lucasponce** [comment]
I think this issue can be used to revisit this logic.
The goal here is that the user should not assume any default.

If the mesh works in "mTLS," the user should get that information, but today there is a mix of implicit/explicit that is affecting the logic implemented in the past.

So, more than checking the edges, I'd think it could be nice to refresh the TLS examples we have and also consider all the potential defaults or explicit "mTLS" situations and check if all "mTLS" logic is valid.

When I performed the Istio mTLS examples/tasks, the above validations added false results when combining the logic with the "default" "mTLS" mode.

So, perhaps this issue can be promoted to a mini-epic to revisit whether the validations flow are correct from the user perspective.

**Comment by jshaughn** [comment]
@hhovsepy Is this blocked given your work on gateway API?

**Comment by hhovsepy** [comment]
@jshaughn yes Gateway API had higher priority for the release, also I need more details on this issue, Still not clear what it needs to be done, and what is wrong with existing mtls validations?

**Comment by jshaughn** [comment]
OK. I am not exactly sure what may be wrong with existing mTLS validations.  Lucas said, "When I performed the Istio mTLS examples/tasks, the above validations added false results when combining the logic with the "default" "mTLS" mode."   I guess that means that when mTLS is explicitly defined that validations worked as he expected, but when implicitly defined via defaults, he saw some inconsistency.  Unfortunately he didn't report any exact reproduction step of link the examples/tasks he performed.  Perhaps he was looking at https://istio.io/latest/docs/tasks/security/authentication/mtls-migration/#lock-down-to-mutual-tls-by-namespace or maybe https://istiobyexample.dev/mtls/.

So I think the task remain here is to revisit and exercise our mTLS validations given various scenarios involving perhas combinations of default and explicit mTLS configuration.   I'm not sure about the priority of the task given that the community may report issues like this, but they may also disable validations that they find annoying.   You can maintain ownership of this task or unassign yourself and we can schedule it for somebody else.
