### ISSUE TITLE
Initial Release of OSSMC

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#5451]
This is to track the steps remaining for OSSMC v0.10, the first community release of the OpenShift Service Mesh Console plugin.

- [x] install guide is up to date
- [x] user guide is up to date
- [x] https://github.com/kiali/kiali/pull/5433
- [x] rh developer blog ready  
- [x] release plugin and operator to quay
- [x] https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1613

**Comment by jmazzitelli** [comment]
To release the plugin, we should try to get it to build multi-arch containers. I have this PR (untested) that 'should' do it:
* https://github.com/kiali/openshift-servicemesh-plugin/pull/78

**Comment by jmazzitelli** [comment]
OLM metadata PR: https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1613

**Comment by jmazzitelli** [comment]
Everything is ready. However, after I deployed via OLM, even though everything is installed and running, the Console doesn't show our Service Mesh stuff. Something is broke, at least on OpenShift 4.10.

I already saw one problem: https://github.com/kiali/openshift-servicemesh-plugin/issues/87

**Comment by jmazzitelli** [comment]
We can close this. We did release an initial version. Might not be working, but we did release it :)
