### ISSUE TITLE
[ambient] initial istio Ambient support

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#5476]
This is to start tracking notes, observations, behavior of Kiali with Istio Ambient.  Any identified sub-tasks can be added below:

Some useful things:
- [Introducing Ambient blog](https://istio.io/latest/blog/2022/introducing-ambient-mesh/)
- [Ambient limitations/readme](https://github.com/istio/istio/blob/experimental-ambient/README.md#limitations)
- [#Ambient channel on Istio Slack](https://istio.slack.com/archives/C041EQL1XMY)
- [Ambient weekly meeting contributor notes](https://docs.google.com/document/d/1SMlwliEnthgq7r2PjpLl1kCq3t8rAMbgu6r_lDAXJ0w/edit#heading=h.o8pz6aqnzzgk)

- Ambient Alpha (Istio 1.18): 
  - [x]  #5504
  - [x] Install bookinfo via our hackscript and Sanity check Kiali pages (set AUTO_INJECTION to false)
  - [x] Install testing demos and #5507 
  - [x] Verify Kiali in Istio 1.18 dev #5910 
  - [x] Verify Kiali using Istio 1.18 Ambient alpha https://github.com/kiali/kiali/issues/6241
  - [x] #5581 
  - [x] Alpha support #5535

- Ambient Alpha with some improvements (Istio 1.19 - 6th september):
  - [x] Beta support  https://github.com/kiali/kiali/issues/6401
  - [x] https://github.com/kiali/kiali/issues/6423
  - [x] #5539 
  - [x] https://github.com/kiali/kiali/pull/6352
  - [x] https://github.com/kiali/kiali/issues/6522
  - [x] https://github.com/kiali/kiali/issues/6579
 
- Istio 1.20: 
  - [x] https://github.com/kiali/kiali/issues/6757
  - [x] #5978  

- Istio 1.21 (Kiali 1.79): 
  - [x] Validate Kiali and Istio Ambient 1.21 dev https://github.com/kiali/kiali/issues/6981
  - [x] Include Waypoint proxy as a default: https://github.com/kiali/kiali/issues/6878
  - [x] Hide waypoint proxies from graph: https://github.com/kiali/kiali/pull/7015 
  - [x] Kiali and Istio Ambient in OpenShift https://github.com/kiali/kiali/issues/7159
  - [x] https://github.com/kiali/kiali/issues/7259

- Istio 1.22 - Ambient L4 beta (Kiali 1.84?): 
  - [x] Envoy logs: https://github.com/kiali/kiali/issues/6898
  - [x] https://github.com/kiali/kiali/issues/6523
  - [x]  Testing Ambient: Create tests to validate the behavior with Istio Ambient. https://github.com/kiali/kiali/issues/5981

- Istio 1.23 
  - [x] L7 Telemetry (reporter=waypoint): https://github.com/kiali/kiali/issues/7344
  - [x] TCP Metrics #6415
  - [x] Adapt action "Enable auto injection" for Ambient Mesh https://github.com/kiali/kiali/issues/7420
  - [x] https://github.com/kiali/kiali/pull/7450
  - [x] https://github.com/kiali/kiali/issues/7432
  - [x] https://github.com/kiali/kiali/issues/7448
  - [x]  Identify waypoint proxies: https://github.com/kiali/kiali/issues/7350
  - [x] Test with 1.23.0 https://github.com/kiali/kiali/issues/7624
  - [x] https://github.com/kiali/kiali/issues/7702
  - [x] (Epic) Simplify Ambient graph: https://github.com/kiali/kiali/issues/7445
  - [x] Support metrics for waypoint and ztunnel edges https://github.com/kiali/kiali/issues/7774  
  - [x] Tests https://github.com/kiali/kiali/issues/7491
  - [x] Docs update with Ambient Graph changes https://github.com/kiali/kiali.io/pull/826

**Comment by jshaughn** [comment]
**This comment can be edited and added to by anyone!**  It is to capture thoughts and questions to be answered about Kiali and Ambient, things that may need to be investigated or may generate sub-tasks.

- [jshaughn] Is it easy for Kiali to identify ambient?
- [jshaughn] Does using just the level4 (just ztunnel secure overlay, no waypoints) still provide istio tcp metrics?
- [jshaughn] Sidecar proxies are still supported in Ambient, but are injection options the same?  And is a missing sidecar still something to care about?
- [jshaughn] Does Kiali need a new view for Waypoint proxies?
- [jshaughn] Will our proxy/access and app log correlation still be feasible with waypoints?

**Comment by jshaughn** [comment]
@josunect Going forward we want to encourage more bounded Epics.  I think we've definitely done enough to merit closing this epic for initial Ambient support.  I'd like to tie this epic to 2.0, so if there is anything remaining to support 2.0 let's call it out here and get it done.  For anything remaining I'd like it to be moved to new, more targeted epics that are either version-based (like, Kiali support for Istio Ambient 1.24) or feature based (like Tracing support for Ambient).

**Comment by josunect** [comment]
> @josunect Going forward we want to encourage more bounded Epics. I think we've definitely done enough to merit closing this epic for initial Ambient support. I'd like to tie this epic to 2.0, so if there is anything remaining to support 2.0 let's call it out here and get it done. For anything remaining I'd like it to be moved to new, more targeted epics that are either version-based (like, Kiali support for Istio Ambient 1.24) or feature based (like Tracing support for Ambient).

The only thing I would like to add - Even if this is not mandatory for 2.0 - is some e2e test support for the waypoint proxy features.
But I'm ok with moving all the remaining issues to another place, I think "Kiali support for Istio Ambient 1.24" is accurate.

**Comment by jshaughn** [comment]
@josunect Great job! I'm closing this Epic!  I've moved the v1.24 goals to a new, more focused epic and added it to the sprint backlog.
