### ISSUE TITLE
Validations for Gateway API objects

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#5501]
Epic: #5026 

The Gateway API objects require validations in Kiali side:
HTTPRoute 
Gateway.

- Validations for k8s Gateways:
  - [X]  No more than one GW per host and port combination [5687](https://github.com/kiali/kiali/pull/5687)
  - [X]  No more than one GW per address [5687](https://github.com/kiali/kiali/pull/5687)
  - [X]  Highlight status rules [5687](https://github.com/kiali/kiali/pull/5687)
  - [x] No more than one GW per host, protocol and port combination per GW. https://github.com/kiali/kiali/issues/5710 
- Validations for k8s httpRoute [#5093 ](https://github.com/kiali/kiali/pull/5693)
  - [x] k8s route referring to non existent gateway https://github.com/kiali/kiali/pull/5693
  - [x] k8s route referring to non existent service https://github.com/kiali/kiali/pull/5706
- [x] References for k8s Gateway: https://github.com/kiali/kiali/issues/5708
- [x] #5709

**Comment by josunect** [comment]
Docs: 

* GW API: https://gateway-api.sigs.k8s.io/concepts/api-overview/#gateway
* Istio Config analysis: https://istio.io/latest/docs/reference/config/analysis/
* Kiali validations: https://kiali.io/docs/features/validations/

### K8sGateway 
---

* More than one GW for the same addresses/Listeners combination
* No matching route found for the listener 


### HTTPRoute
---

* Not matching service found
* Not matching k8sGateway
