### ISSUE TITLE
Investigate multicluster UI/UX changes

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5620]
Epic: #5618 

Determine how the Kiali UI should be updated to support multicluster. Some potential elements include the namespace selector, the mesh config page, the app/workload/service tables.

- [ ] #5913 
- [ ] https://github.com/kiali/kiali/issues/5919
- [ ] https://github.com/kiali/kiali/issues/5920
- [ ] https://github.com/kiali/kiali/issues/5921
- [ ] https://github.com/kiali/kiali/issues/5922
- [ ] https://github.com/kiali/kiali/issues/5923
- [ ] #5932

**Comment by nrfox** [comment]
This needs to be broken down more but can be worked on independently of the backend changes.

**Comment by aljesusg** [comment]
I can work in this one 😉

**Comment by josunect** [comment]
Some other points to define could be: 

- How to display the namespace cards in case of having the same namespace in different clusters: 
  - One per cluster/namespace name combination
  - One card per namespace name, and show the information for all the clusters in the same card. 

I think that if we follow the principle of namespace uniqueness it would make sense to put everything in the same card (second option), but I understand the information could be more confusing - If we want to indicate which cluster are the labels/apps/configs from, or show a warning when some relevant labels or annotations have different values. 

- Different view depending on if we are in single or multicluster 'mode'. (This mode can be detected during runtime, see comment https://github.com/kiali/kiali/issues/5766#issuecomment-1433055352)

**Comment by leandroberetta** [comment]
> 

Personally I would prefer the second one, seems like more straight forward and applies to the namespace sameness as you mention.

Regarding the view depending single or multi cluster, another thing that comes to my mind is that OSSMC will be single cluster (because OpenShift console per se is single cluster) so we have some things there to acommodate for this to work, luckily in the effort of developing a native ossmc we won't have this issues anymore (remember all the logic that we have to indicate that we are in kiosk mode and in the ossmc mode).

**Comment by josunect** [comment]
> > 
> 
> Personally I would prefer the second one, seems like more straight forward and applies to the namespace sameness as you mention.
> 
> Regarding the view depending single or multi cluster, another thing that comes to my mind is that OSSMC will be single cluster (because OpenShift console per se is single cluster) so we have some things there to acommodate for this to work, luckily in the effort of developing a native ossmc we won't have this issues anymore (remember all the logic that we have to indicate that we are in kiosk mode and in the ossmc mode).

Good point. But IMO OSSMC would work the same as using the 'single cluster' view, so it would cover also this scenario, I think

**Comment by leandroberetta** [comment]
> > > 
> > 
> > 
> > Personally I would prefer the second one, seems like more straight forward and applies to the namespace sameness as you mention.
> > Regarding the view depending single or multi cluster, another thing that comes to my mind is that OSSMC will be single cluster (because OpenShift console per se is single cluster) so we have some things there to acommodate for this to work, luckily in the effort of developing a native ossmc we won't have this issues anymore (remember all the logic that we have to indicate that we are in kiosk mode and in the ossmc mode).
> 
> Good point. But IMO OSSMC would work the same as using the 'single cluster' view, so it would cover also this scenario, I think

Yes, but well, this single cluster view mode, will add more validations that can go wrong. I think for the sake of simplificity, we should try to avoid so many rendering logic, if possible!.

**Comment by josunect** [comment]
Some notes from the meeting that we have last Wednesday: 

- If we have the same namespace in two clusters, combine into one: Overview and graph pages. 
- Mesh page: 
  - Always visible
  - Move the Control Plane card? There are more space to show more information
  - Idea: to incorporate a "Topology" view. 
- List view: 
  - Cluster specific rows for "Istio Configs" and "workloads"
  - Combine rows per same namespace in Apps and Services (Services: Should exist the same in all the clusters?) 
- API: Would be the same? (Namespaces combined) 
  - Pros: Keep consistency 
  - Cons: If the API needs to combine the data, this task will be performed more often (There can be N API calls but the backend can cache the data combined)

**Comment by nrfox** [comment]
I'm going to close this issue and move the remaining subtasks into the parent multi-cluster epic
