### ISSUE TITLE
[CI] Gateway API Integration tests.

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#5726]
Add integration tests for Gateway API objects.

- [x] List Gateway and HTTPRoute objects.
- [x] Validations for Gateway details.
- [x] Validations for HTTPRoute details.
