### ISSUE TITLE
Make Kiali compatible with OSSMC

### ISSUE THREAD

**Issue by ferhoyos** [kiali/kiali#6261]
OSSMC plugin is currently in tech preview and it should be promoted to GA. There are multiple requirements to achieve this target:

- The plugin cannot be based on iframes but native React components
- Follow Openshift Dynamic plugin general guidelines (https://docs.openshift.com/container-platform/4.13/web_console/dynamic-plugin/overview-dynamic-plugin.html)

To get rid of iframes and avoid code duplicity, an unmodifiable version of kiali frontend code will be copied. For this reason following modifications need to be addressed to kiali repository to make it compatible with OSSMC plugin.

Phase 1:
- [x] https://github.com/kiali/kiali/issues/6263
- [x] https://github.com/kiali/kiali/issues/6262
- [x] https://github.com/kiali/kiali/issues/6264
- [x] https://github.com/kiali/kiali/issues/6265
- [x] https://github.com/kiali/kiali/issues/6267

Phase 2:
- [x] https://github.com/kiali/kiali/issues/6322
- [x] https://github.com/kiali/kiali/issues/6266 
- [x] https://github.com/kiali/kiali/issues/6349
- [x] https://github.com/kiali/kiali/issues/6270
- [x] https://github.com/kiali/kiali/issues/6268
- [x] https://github.com/kiali/kiali/issues/6417

Phase 3:
- [X] GA Review feedback

**Comment by jshaughn** [comment]
@ferhoyos I think maybe this sub-epic maybe should be marked as Done.  The Phase 3 task is basically complete, as we have no more planned feedback and have a green light for GA.  The Phase N task is not yet on the backlog and I'm not sure about it's priority.  It is not required for GA.

**Comment by ferhoyos** [comment]
Agree with you @jshaughn. Hence closing the sub-epic.
