### ISSUE TITLE
Tempo support improvements

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#6538]
Follow up task with improvements for: https://github.com/kiali/kiali/issues/5849

Epic ref. https://github.com/kiali/kiali/issues/5850 

- [x] https://github.com/kiali/kiali/issues/6592 
- [x] https://github.com/kiali/kiali/issues/6663
- [x] https://github.com/kiali/kiali/issues/6531
- [x] https://github.com/kiali/kiali/issues/6537
- [x] https://github.com/kiali/kiali/issues/6689
- [x] https://github.com/kiali/kiali/issues/6687
- [x] https://github.com/kiali/kiali/issues/6674
- [x] https://github.com/kiali/kiali/issues/6693
- [x] https://github.com/kiali/kiali/issues/6699
- [x] https://github.com/kiali/kiali/issues/6795
- [x] https://github.com/kiali/kiali/issues/6616
- [x] https://github.com/kiali/kiali/issues/6578 
- [x] https://github.com/kiali/kiali/issues/6540
- [x] https://github.com/kiali/kiali/issues/6572
- [x] https://github.com/kiali/kiali/issues/6919
- [x] https://github.com/kiali/kiali/issues/6844
- [x] https://github.com/kiali/kiali/issues/6894
- [x] https://github.com/kiali/kiali/issues/6849
