### ISSUE TITLE
Kiali Performance improvements.

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#7076]
This is a sub-epic to track Kiali performance improvements as a subtasks.

- [x] #4832 
- [x] https://github.com/kiali/kiali/pull/7084
- [x] https://github.com/kiali/kiali/issues/7017
- [x] Optimize fetching 'tls' in Overview page.
- [x] Optimize fetching 'metrics' in Overview page.
- [x] Optimize fetching 'health' in Overview page.

**Comment by nrfox** [comment]
You can see that number of namespaces is a big issue when it comes to perf simply due to the amount of requests the frontend makes to the backend. This can be tested even on minikube by creating ~200 namespaces and then trying to load the graph or overview pages. Solving https://github.com/kiali/kiali/issues/4832 would make this much better. Adding it to the list here.

**Comment by hhovsepy** [comment]
Kiali performance improvements are finished at this stage, in a scope of the epic.
More improvements could be done are separate tasks in the future.

**Comment by jshaughn** [comment]
Nice job managing this epic @hhovsepy!
