### ISSUE TITLE
Cypress testsuite for performance tests. All list and details pages including all table. Read only tests.

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#7088]
The following pages needs to be covered:
- [x] Apps list - selected namespaces, all namespaces
- [x] App Details - all tabs
- [x] Workloads list - selected namespaces, all namespaces
- [x] Workload Details - all tabs
- [x] Services list - selected namespaces, all namespaces
- [x] Service Details - all tabs
- [x] Istio Configs list  - selected namespaces, all namespaces
- [x] Istio Config Details
