### ISSUE TITLE
Perf tests on QE Jenkins upstream-istio-pipeline

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#7097]
In order to run Kiali perf tests on QE testing environment
- [x] Define the testing environment size and the demo apps. Number of namespaces, pods and the traffic.
- [x] Create env data setup job. It should create testing demos.
- [x] #7247
- [x] Include the Jenkins job into upstream-istio-pipeline by default disabled.
- [x] Define baselines for performance tests

**Comment by hhovsepy** [comment]
Attached Kiali perf tests measurement results after the performance improvements, for 10, 50, 200, 300, 500 and 800 namespaces, 1 service and 2 workloads in each namespace.
[10.txt](https://github.com/kiali/kiali/files/15375876/10.txt)
[50.txt](https://github.com/kiali/kiali/files/15375874/50.txt)
[200.txt](https://github.com/kiali/kiali/files/15375870/200.txt)
[300.txt](https://github.com/kiali/kiali/files/15375875/300.txt)
[500.txt](https://github.com/kiali/kiali/files/15375872/500.txt)
[800.txt](https://github.com/kiali/kiali/files/15375871/800.txt)

**Comment by hhovsepy** [comment]
Perf test results for 5 namespaces with 10 services: [5-10.txt](https://github.com/kiali/kiali/files/15495733/5-10.txt)
50 namespaces with 1 service: [50.txt](https://github.com/kiali/kiali/files/15495734/50.txt)

Here we have ~10% faster load time when 5 namespaces have 50 services overall.
