### ISSUE TITLE
Workload Entry and Workload Group support for VMs

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#7107]
There are several issues around Workload Group and/or Workload Entry support for VMs.  Kiali should have some type of support for these configurations.  I'm adding this Epic to consolidate the current issues.

- [x] https://github.com/kiali/kiali/issues/4169
- [x] https://github.com/kiali/kiali/issues/5886
- [x] https://github.com/kiali/kiali/issues/5887
- [x] WorkloadGroup to WorkloadEntry cross reference
- [x] #8058
- [x] WokloadGroup references.
- [x] Workload references.

**Comment by hhovsepy** [comment]
Will be released in upcoming Kiali v2.5.
