### ISSUE TITLE
[Ambient] Improve Ambient Graph

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#7445]
### What do you want to improve?
Visualize waypoint proxies in the graph

### What is the current behavior?
Waypoint proxies are included in the graph, but some edges are missing, no double edges because of problems highlighting the node graph, and maybe they shouldn't be represented as a node. 
Ref. https://github.com/istio/ztunnel/issues/1128 

### What is the new behavior?
Think the best way to represent these elements in the graph. 
Ref. https://github.com/kiali/kiali/pull/7560

Related PRs:

- Waypoints: 
  - [x] Waypoint node icons: https://github.com/kiali/kiali/pull/7575
  - [x] Double edges for waypoints: https://github.com/kiali/kiali/pull/7593
  - [x] Simplify Ambient Graph: https://github.com/kiali/kiali/pull/7742
  - [x] Summary panel for double edges: https://github.com/kiali/kiali/pull/7719
  - [x] Waypoint nodes should be workload type, not app: https://github.com/kiali/kiali/issues/7702 
  - [x] Combined edges: https://github.com/kiali/kiali/pull/7693
  - [x] https://github.com/kiali/kiali/pull/7766
  - [x] https://github.com/kiali/kiali/issues/7774
  - [x] Combined edges? (for now we will just go with custom bendpoints, see #7780).
- zTunnel: 
  - [x] Visualize ztunnel in the Graph: https://github.com/kiali/kiali/issues/6900

**Comment by jshaughn** [comment]
I'm reclassifying as a research topic, I don't think we need to think about this and what the best approach may be.

**Comment by josunect** [comment]
![image](https://github.com/user-attachments/assets/45bc76db-f11f-4e43-aff7-014b9ba36bd3)

The problem when there is a waypoint proxy seems to be that the waypoint "hides" the source App, because it is going to be waypoint. So all the edges are hidden when we hide the waypoint proxy for the tcp graph: 

![image](https://github.com/user-attachments/assets/7c6d83c0-4563-485c-a914-77e2bfb93601)

https://github.com/kiali/kiali/blob/master/graph/telemetry/istio/istio.go#L363

**Comment by jshaughn** [comment]
@josunect , I've been looking at the ambient bookinfo install and thinking about what we may want to do to improve the ambient graphs.  As a note,  I went back to looking at things without even running the current ambient appender, just to kind of get a baseline.  A couple of thoughts:

- I think the majority of issues come from how ztunnel-waypoint telem interacts with the Show Service Nodes option (i.e. service node injection).  And by "ztunnel waypoint" I mean the z-tunnel telem that has either a waypoint source or destination.  In short, I don't think we should be injecting service nodes on these edges.  Service node injection is really targeted more at L7-level proxy features.  The ztunnel edges to/from the waypoint are really workload-to-workload.
  - The main technical issue is avoiding the injection on these edges.  There are two options:
     1.  Prevent the the injection during the main graph generation.  The downside to this approach is that we need to know if the source or dest workload is a waypoint.  This isn't possible given the current telem because all we have are names, and waypoint names are configurable.  I think we'd have to gather up the waypoint workload names and do a match. We have historically avoided having to combine config and telem in the main graph generation, we leave that to the appenders.
     2. Remove the injection in the ambient appender.  This would be the more desirable location to add logic, but I think it may be impossible.  The appender has no way to know the original source or dest workload.  It only has the injected service node, which may have multiple edges going into it.
  - So I think we may have to break with tradition and make the main graph generator aware of waypoint workload names.  If we do this then the edges to waypoints will always be workload to workload, which creates a cleaner graph.
  - I think we will still need/want the bi-directional edges, but I think they will be between the waypoint and the source or dest workload.
  - I think this will reduce the number of unified "ambient" edges, but there are still use cases where there will be both ztunnel and non-ztunnel edges between the same nodes.
- We have been talking about somehow showing waypoint on HTTP edges (reporter="waypoint").  But actually, even TCP data may be going through the waypoint. For example, if you add mongodb to bookinfo, the mongodb workload also uses the waypoint, because it is in the bookinfo namespace, which has been assigned the waypoint.  Note, I created a PR to stop this, but having mongodb opt-out.  Anyway, I think we may want to add waypoint information to the destination node, whose service,  I think, is the service which uses the waypoint.  We could use that to possibly decorate the edge, or just the destination node.

I didn't write any code, I'm just thinking about things.
