### ISSUE TITLE
Properly use Group + Version + Kind for kube resources

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#7457]
Kiali relies on the `Kind` field to be unique across all kube resources but only `Group` + `Version` + `Kind` is unique. This has already been an issue with the `Gateway` kind when adding gateway api support. We keep track of the "internal" kind and the "real" kind separately when we want to display an object. Kiali should instead just use the full GVK (Group,Version,Kind) internally and externally when displaying resources to users. If externally we don't want to use the full GVK when displaying resources, Kiali can choose how to disambiguate between two resources with the same `Kind` but at the very least internally objects should use the full GVK.

- [x] Istio Config object CRUD API requests in `group/version/kind` format.
- [x] UI changes to have all URL references to Istio Configs in `group/version/kind` format.
- [x] Istio Config validations response json change to GVK format.
- [x] Istio Config List response to list configs in GVK keys not hardcoded plural properties like 'k8sgateways'. TODO
