### ISSUE TITLE
Kiali 2.0 Release

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#7561]
There are some major enhancements and changing that are coming that should probably warrant Kiali moving to the next major release version (2.0).

Required:
- [x]  https://github.com/kiali/openshift-servicemesh-plugin/issues/99
- [x] #7445  
- [x] [Show certificate information per controlplane](https://github.com/kiali/kiali/issues/7456)
- [x] Update any necessary release/CI scripts for 2.0 (leandro handling this)
- [x] Medium blog to support the major release (jay handling this)
- [x] [A new graph extension framework allowing third-parties to link their telemetry into Kiali graph](https://github.com/kiali/kiali/issues/7485)
- [x] https://github.com/kiali/kiali/issues/7751
- [x] ~The Kiali CR config and helm chart configs move to standard camelCase (as opposed to snake_case)~
- [x] Namespaces are discovered and configured via set-based selectors (as opposed to the myriad of ways things are done today, e.g. accessible_namespaces and the api.namespaces includes/excludes - all of which are going away). See [KEP "namespace discovery"](https://github.com/kiali/kiali/blob/master/design/KEPS/namespace-discovery/proposal.md)
(https://github.com/kiali/kiali/pull/7486))
- [x] [Improve URL configuration](https://github.com/kiali/kiali/issues/7745)
- [x] [OLM metadata bumped to 2.0](https://github.com/kiali/kiali-operator/pull/819)

Want:
- [x] #7441

**Comment by jmazzitelli** [comment]
I did some thinking around the camelCase stuff and I'm hedging on that:

1. It doesn't affect functionality one way or the other, so there is no "bug" or "enhancement" this would be addressing
2. The only reason we care about camelCase is because that's how k8s resources are; so it is just to conform to a de-facto common style, but there is no k8s syntax rule we are violating
3. The changes will affect past users. If I have 1.73 installed, and want to upgrade, I now have to alter my entire Kiali CR.  This will at least be annoying if not introduce potential problems if I fat-finger the conversion. And if I want to downgrade for some reason, I have to convert back (more annoyance).
4. It will require us to change a lot of the operator Ansible code, which would be ripe for introducing bugs.
4a. What about supporting both? That would require adding more code that again is ripe for bugginess, and for what gain? Basically, #2.

All this for a mere style change to the configuration file whose current style is one that no one seems to care about in the first place (e.g. I never heard a single user complain about this, or say they did not want to use snake_case).

**Comment by jshaughn** [comment]
Closing, all needs and wants have been addressed!
