### ISSUE TITLE
[Tempo] Review performance

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#7769]
### What do you want to improve?
Review Tempo performance

### What is the current behavior?
With the sail hack script, the behavior is flaky. 

### What is the new behavior?
Performance improved in Tempo

Tasks:

- [x] https://github.com/kiali/kiali/pull/7768
- [x] Review best approaches (Like from Grafana, etc), default Tempo config, ... Document "Tempo tuning" https://github.com/kiali/kiali.io/pull/830
  - https://grafana.com/docs/tempo/latest/operations/backend_search/
  - https://grafana.com/docs/tempo/latest/operations/dedicated_columns/
  - https://grafana.com/docs/tempo/latest/operations/caching/
- [x] Improve Tempo client in Kiali https://github.com/kiali/kiali/pull/7854 
- [x] Test Tempo with multi tenancy in OpenShift (Updated blog post for reference)
- [x] Allow users to set trace query limits https://github.com/kiali/kiali/pull/7895
- [x] Optimize Tempo query: https://github.com/kiali/kiali/issues/7903
- [x] https://github.com/kiali/kiali/pull/7923

**Comment by josunect** [comment]
I think the main issue with Tempo is, that in the Tempo operator, they specify this resources as the default (https://docs.redhat.com/en/documentation/openshift_container_platform/4.15/html/distributed_tracing/distributed-tracing-platform-tempo#distr-tracing-tempo-install-tempostack-web-console_dist-tracing-tempo-installing):
 ``` resources:
    total:
      limits:
        memory: 2Gi
        cpu: 2000m 
```

These resources are for all the tempo components, and I think they are not enough to run just simple queries. If you run this query just 5 times from the grafana UI, you got a OOMKilled:
![image](https://github.com/user-attachments/assets/635a9575-9509-4879-92c5-21bbd480de20)
![image](https://github.com/user-attachments/assets/126637a1-e700-4c6a-9934-42fa3ea1bf57)

Without specifying those limits, the query that we do: 
![image](https://github.com/user-attachments/assets/381ac3df-ff2a-4952-b193-295bb5a8ad53)

Takes between 300 ~= 400 ms.

**Comment by jshaughn** [comment]
That's good data.  Without the limits can you tell how much memory gets consumed? That seems like a pretty quick OOM for 2gb of mem, but I guess that's what happens.

**Comment by josunect** [comment]
> That's good data. Without the limits can you tell how much memory gets consumed? That seems like a pretty quick OOM for 2gb of mem, but I guess that's what happens.

So, it looks like it might be a CPU bottleneck, as I see in the last tests are no more than 1300 MB used (That's using some prometheus metrics):
![image](https://github.com/user-attachments/assets/72fc3073-7015-4ef5-8cd2-042ca01b86ca)

This is the grafana dashboard used. It was modified to use the rate and adding the summary of all the components: 
[Tempo resources consumption by pod-1730286418280.json](https://github.com/user-attachments/files/17571179/Tempo.resources.consumption.by.pod-1730286418280.json)

That's a comparason using the limits and without the limits (The peak at the end): 
![image](https://github.com/user-attachments/assets/c147d991-1707-41e8-b0fd-14def767f6ba)

I see it uses (The orange is the sum) around 0.12 CPU and 2000 MB of memory.

**Comment by jshaughn** [comment]
Interesting, so maybe the cpu limit is the only limit to be raised or removed.

**Comment by josunect** [comment]
All issues merged
