### ISSUE TITLE
[ambient] ambient v1.24 support

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#7826]
This epic tracks our ambient goals roughly based on the Istio 1.24 release.

- Istio 1.24 (Or Later): Ambient L7 beta: 
  - [x] [Test istio 1.24 Ambient with Kiali](https://github.com/kiali/kiali/issues/7897)
  - [x] Include information to help troubleshooting https://github.com/kiali/kiali/pull/7970
  - [x] Waypoint proxy: Add information like: List of workloads/services, if it applies to service/workload,  https://github.com/kiali/kiali/issues/7999
  - [x] Tracing in Ambient [No span traces](https://github.com/kiali/kiali/issues/5979)
  - [x] [Waypoint proxy: Visualize it in the Mesh Page](https://github.com/kiali/kiali/issues/8054)
  - [x] Waypoint proxy: Use an "effective" field. A workload can have more than one waypoints, but just one of them should be effective. https://github.com/kiali/kiali/issues/8157
  - [x] [Waypoint proxy logs](https://github.com/kiali/kiali/issues/7899)
  - [x] [Waypoint use cases](https://github.com/kiali/kiali/issues/7499)
  - [x] ztunnel metrics https://github.com/kiali/kiali/issues/8024
  - [ ]  Tracing overlay https://github.com/kiali/kiali/issues/8108
  - [ ] Improve Waypoint/ztunnel tab: Add filter https://github.com/kiali/kiali/issues/7996
  - [ ] [Detect issues in the mesh](https://github.com/kiali/kiali/issues/6041)
  - [x] Add test coverage: https://github.com/kiali/kiali/issues/8184 

- Others:
  - [ ] [Some istio configs should not be created if the workload doesn't have a waypoint (Ex. http authorization policies)](https://github.com/kiali/kiali/issues/7900)
  - [ ] [Add/Remove from Ambient from the overview page for the Ambient namespaces](https://github.com/kiali/kiali/issues/7901)
  - [ ] [Create waypoint proxy using Kiali wizards](https://github.com/kiali/kiali/issues/6890)
  - [x] [Hack scripts to install Ambient for demos](https://github.com/kiali/kiali/issues/5980)
  - [ ] GA. The idea when Ambient is GA is that everything would be in the mesh, so probably it wouldn't make sense to 1) Identify Ambient globally. 2) The message "out of mesh". It can be replaced by "No proxy". 
  - [ ] Waypoint doesn't need to be Istio/Envoy: With Gateway API and GAMMA, any compliant implementation can act as a waypoint. 
  - ztunnel logs could fail if the user doesn't have permissions to istio-system
Ambient detection mode: That would be worth watching for changes: https://github.com/istio/istio/issues/53578
  - Deployment models: Is there any consideration to take into account for different deployment models (i.e. Multicluster) (ATM Multicluster is something TBD for Ambient)
  - Support Istio revisions in Ambient

**Comment by josunect** [comment]
Closed for Istio 1.24. 
New epic: https://github.com/kiali/kiali/issues/8250
